- aria-practices.html
<kbd> close tag was missing /
(Still a git/github noob - hope I got the fork/branch/pr stuff right.)
> Close kbd tag.

- examples/radio/radio-1/radio-1.html
- examples/radio/radio-2/radio-2.html
1. Updated documentation to use latest format
2. Fixed bug in radio 1 example, second radio group was not initialized
> Update Radio group examples

- examples/css/table.css
> Example css for tables 

- aria-practices.html
Hopefully this fixes all of the broken links - it is hard to test until we get the gh pages version.
There were a couple of extra changes I had to make to add notes - or remove links to content which hasn't yet been written - and then a few lines got changed due to my editorconfig (spaces removed at the end of lines) but they shouldn't affect the output.
> Fix broken links

- examples/treeview/treeview-1/treeview-1a.html
- examples/treeview/treeview-1/treeview-1b.html
- examples/treeview/treeview-2/treeview-2a.html
- examples/treeview/treeview-2/treeview-2b.html
- fix table header issues
- add links to move between examples
- edited the descriptions
> updated tree view to fix table and add links

- examples/accordion/accordion1.html
Filled in the roles/properties section and updated the aria-level of the accordion to 3
> Updates for the accordion example. 

- aria-practices.html
- examples/landmarks/css/bootstrap.css
- examples/menu-button/menu-button-1/css/menuButtonAction.css
> Publication link fixes

- examples/button/button.html
> Fixing tabindex for example button

- examples/button/button.html
- examples/button/js/button.js
Made changes based on the discussion last weeks teleconference
> Updated button example

- examples/coding-template/Example-Template.html
- examples/js/examples.js
Updated code generation script to:
1. Exclude container element with id
2. Added the inclusion of comments in source code
3. Fixed bug of HTML code in script elements not being included
> Updated code generation script 

- examples/slider/css/slider.css
- examples/slider/css/text-slider.css
- examples/slider/css/vertical-slider.css
- examples/slider/js/slider.js
- examples/slider/js/text-slider.js
- examples/slider/js/vertical-slider.js
- examples/slider/slider-1.html
- examples/slider/slider-2.html
Also improves focus styling of rail
> Updated slider to include tab index in source code 

- examples/dialog-modal/css/dialog.css
Addressing feedback on issue #321. Updated styling of the dialog to be more responsive.
> fix overflow style of dialog

- aria-practices.html
“ssection” should be “section”
> Spelling correction

- .travis.yml
Separating this out from the gh-pages PR since it will help whether that lands or not
> chore: add 3 retries to spec-generator on Travis

- examples/listbox/css/listbox.css
- examples/listbox/listbox-rearrangeable.html
Updated style of toolbar and buttons
> Styled buttons and toolbar in listbox example

- examples/accordion/js/accordion.js
Removed ES6 JS and make compatible with IE11, as mentioned in #401
> #401 IE11 Compatible JS

- examples/accordion/accordion.html
Fixes issue https://github.com/w3c/aria-practices/issues/475
ping @mcking65
> Accordion Example: Update documentation for change to button from link

- examples/checkbox/css/checkbox.css
Replaces the horizontal line with a skewed line.
> 471: New design for mixed state checkbox

- examples/grid/js/menuButton.js
- examples/toolbar/js/menuButton.js
- examples/treeview/treeview-1/js/tree.js
- examples/treeview/treeview-2/js/treeLinks.js
Just fixes a minor typo across multiple comments s/initializ/initialize/.
> Fixed typo in a comment.

- aria-practices.html
- examples/table/css/table.css
- examples/table/table.html
1. Initial draft of table design pattern for issue #90.
2. Initial draft of table example HTML for issue #242; still needs CSS.
> Table Design Pattern and Example: Initial Draft

- examples/combobox/aria1.1pattern/js/grid-combobox.js
Small refactor to determine appropriate row by moving logic to a reusable method, which can be used for either UP/DOWN or LEFT/RIGHT arrow keys.
> Issue 499: Fix LEFT/ RIGHT arrows wrapping to proper row

- examples/toolbar/js/toolbar.js
- examples/toolbar/toolbar.html
As mentioned in #540, removed use of `aria-selected`
> Remove use of aria-selected

- examples/grid/LayoutGrids.html
Just re-ran the validator and found this one
> bug(grid): unclosed paragraph tag

- examples/table/css/table.css
- examples/table/table.html
> added table styling and two more rows to table

- examples/dialog-modal/dialog.html
Fixes #613. This only adds the id back in so that the HTML source is generated.
> re-add dialog_layer id

- examples/combobox/aria1.1pattern/grid-combo.html
- examples/combobox/aria1.1pattern/js/grid-combobox.js
- examples/combobox/aria1.1pattern/js/listbox-combobox.js
- examples/combobox/aria1.1pattern/listbox-combo.html
Closes https://github.com/w3c/aria-practices/issues/622
> Fix combobox examples markup, fix IE/Edge "null" entry bug

- examples/grid/LayoutGrids.html
Fixed error "Bad value true for attribute disabled on element button." described in #579 
Fixed Nu HTML warnings "The type attribute is unnecessary for JavaScript resources."
> Fix html validation issues in layoutgrid #579

- examples/toolbar/toolbar.html
Cherry-picked this out of #421 since it can land while that's still being discussed
> bug(toolbar): bad mime type for CSS links

- examples/treeview/treeview-1/css/tree.css
- examples/treeview/treeview-2/css/treeLinks.css
Fix a disgusting blinking effect appearing on hover to the right of a treeitem.
> Treeview examples: fix blink on hover for issue #712

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/jongund/aria-practices/pull/714.html" title="Last updated on Jun 16, 2018, 1:19 AM GMT (9dfba29)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/714/dc2a614...jongund:9dfba29.html" title="Last updated on Jun 16, 2018, 1:19 AM GMT (9dfba29)">Diff</a>
> Initial draft of Treegrid design pattern

- examples/radio/css/radio.css
Updated keyboard focus styling to include border around both the radio button and label
Updated hover style to highlight both the radio button and the label
> Radio groups: Fix focus styling issue 568 

- examples/menubar/menubar-2/menubar-2.html
@mcking65 -- another should be easy review/merge :)
> Add data-test-id to menubar-2.html example page

- examples/combobox/aria1.1pattern/listbox-combo.html
- test/index.js
- test/tests/link.js
- test/tests/listbox-combo.js
- test/util/confirmAriaDescendantFocus.js
- test/util/confirmAriaLabelledby.js
- test/util/confirmAttributeValue.js
**New tests and abstractions:**
- test/tests/listbox-combobox.js
- tests for combobox/aria1.1pattern/listbox-combo.html
- test/utils/check*.js
- added test abstractions
**Minor fixes:**
- test/index.js
- fixed bug in test name
- removed objects from t.context
- test/tests/link.js
- fixed reference to t.context.By
- ran lint --fix
> Tests for combobox/aria1.1pattern/listbox-combo.html

- examples/combobox/aria1.1pattern/listbox-combo.html
- examples/grid/LayoutGrids.html
Hi @mcking65 -- per our discussion, here is a PR to master with the changes to the example pages themselves. This commit only add "data-test-id" to the appropriate tables.
> Changes to example page html for listbox-combo.html and LayoutGrid.html

- examples/dialog-modal/dialog.html
- examples/menu-button/menu-button-actions.html
- examples/slider/slider-1.html
- examples/tabs/tabs-1/tabs.html
- examples/treeview/treeview-1/treeview-1a.html
Hi @mcking65 -- thought I'd get a week ahead on the data-test-ids as you will be out all of next week :) If you could review/merge before end of day Friday that would be great.
> Add data-test-ids for next set of examples

- test/tests/LayoutGrids.js
This replace PR: https://github.com/w3c/aria-practices/pull/755
I addressed all your feedback here, @tatermelon ! The commits are in the same order, so you reviewed up to the "Satisfy linter" commit.
> Add tests for grids/LayoutGrids.html

- test/tests/LayoutGrids.js
- test/tests/listbox-combo.js
- test/tests/menubar-2.js
Addressing feedback for  #784, #767 and #783
> Address feedback for listbox-combo.js, LayoutGrid.js and menubar-2.js

- test/tests/treeview-1a.js
- test/util/assertAriaLabelledby.js
Addressed feedback from #801 -- @jessebeach @sh0ji
> Address feedback for test/tests/treeview-1a.js

- examples/accordion/accordion.html
- examples/button/button.html
- examples/checkbox/checkbox-1/checkbox-1.html
- examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
- examples/disclosure/disclosure-faq.html
- examples/listbox/listbox-scrollable.html
- examples/radio/radio-1/radio-1.html
- examples/toolbar/toolbar.html
> Add data-test-id attribute to examples

- test/tests/slider-1.js
- test/util/assertAriaRoles.js
> Tests for example slider/slider-1.html

- aria-practices-DeletedSectionsArchive.html
- examples/checkbox/checkbox-1/checkbox-1.html
- examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
- examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
- examples/combobox/aria1.0pattern/combobox-autocomplete-none.html
- examples/menubar/menubar-1/mb-about.html
- examples/menubar/menubar-1/mb-arts.html
Split the markup fixes from #779 per @mcking65
> Fix vnu examples markup

- examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
- examples/combobox/aria1.1pattern/listbox-combo.html
I found a couple typos in the data-test-ids I added @mcking65
> Update data-test-ids for regression tests

- test/tests/combobox-autocomplete-both.js
- test/tests/listbox-combo.js
hi @mcking65 -- we discussed commenting out the failing tests in order to get successful CI runs, here is a PR for it.
@jessebeach can you do a quick review?
> Comment out expected failing tests from regression tests

- examples/dialog-modal/alertdialog.html
> Replace lorem ipsum placeholder with more descriptive text

- test/tests/combobox-autocomplete-both.js
- test/tests/combobox-autocomplete-list.js
- test/tests/combobox-autocomplete-none.js
- test/tests/grid-combo.js
[combobox/aria1.1pattern/grid-combo.html](https://w3c.github.io/aria-practices/examples/combobox/aria1.1pattern/grid-combo.html)
[combobox/aria1.0pattern/combobox-autocomplete-none.html](https://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-none.html)
[combobox/aria1.0pattern/combobox-autocomplete-list.html](https://w3c.github.io/aria-practices/examples/combobox/aria1.0pattern/combobox-autocomplete-list.html)
> Add tests for all remaining combobox examples

- examples/alert/alert.html
- examples/breadcrumb/index.html
- examples/treeview/treeview-1/treeview-1b.html
- examples/treeview/treeview-2/treeview-2a.html
- examples/treeview/treeview-2/treeview-2b.html
Hi @mcking65 -- if you could review and merge this soon, that would be great!
> Add data-test-ids for regression tests

- .travis.yml
Related to #848
This will add 2 separate builds to separate out the linting and HTML validation so there are separate results reported
> chore: Use Travis Build stages

- test/tests/alert.js
- test/tests/breadcrumb.js
- test/tests/table.js
Add tests for:
* example/breadcrumb/index.html
* example/alert/alert.html
* example/table/table.html
> Regression tests for breadcrumb, alert and table

- .travis.yml
Minor for the Checks API and the travis build result page
> chore: Add Travis job name for AVA tests

- test/tests/treeview-1a.js
- test/tests/treeview-1b.js
- test/tests/treeview-2a.js
- test/tests/treeview-2b.js
- [treeview/treeview-1/treeview-1b.html](https://w3c.github.io/aria-practices/examples/treeview/treeview-1/treeview-1b.html)
- [treeview/treeview-2/treeview-2a.html](https://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2a.html)
- [treeview/treeview-2/treeview-2b.html](https://w3c.github.io/aria-practices/examples/treeview/treeview-2/treeview-2b.html)
> Add tests for all remaining treeview examples

- test/tests/breadcrumb.js
- test/tests/combobox-autocomplete-both.js
- test/tests/combobox-autocomplete-list.js
- test/tests/combobox-autocomplete-none.js
- test/tests/link.js
- test/tests/menubar-2.js
- test/tests/radio-1.js
- test/tests/table.js
- test/tests/tabs.js
- test/tests/toolbar.js
- test/tests/treegrid-1.js
- test/util/assertAriaLabelExists.js
- test/util/assertAriaRoles.js
- test/util/assertAttributeValues.js
Tests for: https://w3c.github.io/aria-practices/examples/treegrid/treegrid-1.html
This PR also adds a "assertAriaLabel" helped function and updates old tests that can us it.
> Add regression tests for treegrid example

- examples/accordion/accordion.html
- examples/accordion/css/accordion.css
- examples/accordion/js/accordion.js
* Resolves #815 
* Improves focus styling to make it more obvious that the accordion is a composite-like structure that has a degree of focus management.
> Issue815 accordion restructure

- test/tests/menu-button-actions-active-descendant.js
- test/tests/menu-button-actions.js
- test/tests/menu-button-links.js
- test/util/assertAriaActivedescendant.js
- test/util/assertAriaSelectedAndActivedescendant.js
This adds tests for:
- menu-button/menu-button-links.html 
- menu-button/menu-button-actions-active-descendant.html
> Add tests for remaining menu-button examples

- .vnurc
> chore: Remove VNU exclusions for accordion

- test/tests/combobox-autocomplete-both.js
- test/tests/combobox-autocomplete-list.js
- test/tests/combobox-autocomplete-none.js
- test/tests/dataGrids.js
- test/tests/treegrid-1.js
- test/util/assertAriaControls.js
- test/util/assertAriaLabelExists.js
- test/util/assertAttributeDNE.js
- test/util/assertRovingTabindex.js
* Using .failing for treegrid test (this one test got lost in the sea of PRs last week)
* Remove t.log from datagrid test
> Regression test clean up

- examples/menubar/menubar-1/menubar-1.html
> Apply role="none" to <li> elements in menubar

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/977.html" title="Last updated on Jan 28, 2019, 5:12 PM UTC (e430ee4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/977/b36ca5a...e430ee4.html" title="Last updated on Jan 28, 2019, 5:12 PM UTC (e430ee4)">Diff</a>
> adjust affiliations in acknowledgements

- aria-practices.html
- examples/carousel/carousel-1/carousel-1.html
- examples/landmarks/css/bootstrap.css
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/984.html" title="Last updated on Feb 6, 2019, 3:38 PM UTC (f36bf5c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/984/a37d8a1...f36bf5c.html" title="Last updated on Feb 6, 2019, 3:38 PM UTC (f36bf5c)">Diff</a>
> fix broken links reported by link checker

- respec-config.js
Following my recent name change: change Michiel to Zoë in the editor section.
> Change Michiel → Zoë

- examples/google/alert.html
- examples/google/alertdialog-modal.html
- examples/google/log.html
- examples/google/status.html
- examples/google/switch.html
As per email from Jemma, switch and alert are for comparison to APG's already existing examples. APG does not have log or status yet.
1 contributor who doesn't have a GitHub accounts is Scott Chenier.
alert.html: Scott (primary author). +@0ddfell0w +@slauriat (reviewers)
log.html: +@katiehockman (primary author). +@0ddfell0w (contributor). +@kbae00, +@slauriat, +@cshimy (reviewers)
status.html: +@cshimy (primary author). +@katiehockman +@slauriat (contributors). +@kbae00 +@cshimy (reviewers)
alertdialog-modal.html: +@0ddfell0w (primary author). +@philipjia123 +@katiehockman (contributors). +@slauriat +@katiehockman +@kbae00 +@0ddfell0w (reviewers)
> Adding example files for alert, modal alert dialog, log, status and switch

- .vnurc
> chore: Unignore "rel" linting

- aria-practices.html
WIP to address feedback provided in issue #1050.
[View revised section 5 in the issue1050-naming-describing-feedback branch](https://raw.githack.com/w3c/aria-practices/issue1050-naming-describing-feedback/aria-practices.html#names_and_descriptions)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1062.html" title="Last updated on Jul 11, 2019, 1:46 AM UTC (1c1f322)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1062/19f3cdf...1c1f322.html" title="Last updated on Jul 11, 2019, 1:46 AM UTC (1c1f322)">Diff</a>
> Naming and Describing Section: Revisions to address feedback in issue 1050

- examples/dialog-modal/datepicker-dialog.html
- examples/dialog-modal/js/calendar-button.js
- examples/dialog-modal/js/datepicker-day.js
- examples/dialog-modal/js/datepicker.js
- test/tests/datepicker-dialog.js
This PR takes @jongund's work in https://github.com/w3c/aria-practices/pull/1073 and cherry-picked it onto master.
Fixes issues in #1072
[View the example HTML file in this branch using raw.githack](https://raw.githack.com/w3c/aria-practices/issue1072-clean-datepicker-dialog-aria-selected-patch/examples/dialog-modal/datepicker-dialog.html)
> Issue1072 datepicker dialog aria selected patch (update onto master)

- aria-practices.html
- examples/listbox/listbox-collapsible.html
- examples/listbox/listbox-rearrangeable.html
- examples/menubar/menubar-1/menubar-1.html
- examples/menubar/menubar-2/menubar-2.html
- examples/table/table.html
- examples/treeview/treeview-2/treeview-2a.html
- examples/treeview/treeview-2/treeview-2b.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1080.html" title="Last updated on Jul 13, 2019, 5:03 AM UTC (b0b829c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1080/8a3fea1...b0b829c.html" title="Last updated on Jul 13, 2019, 5:03 AM UTC (b0b829c)">Diff</a>
> Editorial: Remove outdated links to feedback issues

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1089.html" title="Last updated on Jul 15, 2019, 7:02 AM UTC (5aae92a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1089/c45c43b...5aae92a.html" title="Last updated on Jul 15, 2019, 7:02 AM UTC (5aae92a)">Diff</a>
> Add change log to appendix

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1090.html" title="Last updated on Jul 15, 2019, 7:47 AM UTC (cb702f2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1090/e8099ca...cb702f2.html" title="Last updated on Jul 15, 2019, 7:47 AM UTC (cb702f2)">Diff</a>
> Update acknowledgements and participants list

- aria-practices.html
- examples/carousel/carousel-1.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1091.html" title="Last updated on Jul 15, 2019, 8:23 AM UTC (c16a7dc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1091/7633c5d...c16a7dc.html" title="Last updated on Jul 15, 2019, 8:23 AM UTC (c16a7dc)">Diff</a>
> Carousel and Spin Button: Fix links between patterns and example pages

- aria-practices.html
- examples/carousel/carousel-1.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1093.html" title="Last updated on Jul 15, 2019, 11:23 AM UTC (d783b34)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1093/c841790...d783b34.html" title="Last updated on Jul 15, 2019, 11:23 AM UTC (d783b34)">Diff</a>
> Update apg-1.1 with latest changes from master

- examples/slider/js/multithumb-slider.js
- examples/slider/js/slider.js
- examples/slider/js/text-slider.js
- examples/slider/js/vertical-slider.js
- scripts/reference-tables.js
- test/tests/menubar-1.js
- test/tests/menubar-2.js
Minor whitespace changes being caught by new version of ESLint
> chore: Run eslint fix for new version

- aria-practices.html
Resolves #1106
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1113.html" title="Last updated on Aug 25, 2019, 3:13 AM UTC (c99adb0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1113/fbe1357...c99adb0.html" title="Last updated on Aug 25, 2019, 3:13 AM UTC (c99adb0)">Diff</a>
> Add roles to structural roles section

- aria-practices.html
closes #1107
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1140.html" title="Last updated on Aug 31, 2019, 9:20 AM UTC (c86b5ef)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1140/0c02bec...c86b5ef.html" title="Last updated on Aug 31, 2019, 9:20 AM UTC (c86b5ef)">Diff</a>
> Structural Roles Section: Add deletion and insertion roles

- aria-practices.html
closes #1145
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1146.html" title="Last updated on Sep 1, 2019, 3:13 AM UTC (87ab072)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1146/0376e86...87ab072.html" title="Last updated on Sep 1, 2019, 3:13 AM UTC (87ab072)">Diff</a>
> Add Generic Role

- examples/button/button.html
- examples/button/button_idl.html
- examples/button/js/button_idl.js
Closes issue #727 
- clarify purpose of example
- remove "similar examples" list
- set reflected attributes in init()
- add "equivalent to" comments
> Button Examples (IDL Version): Clarify purpose and code for issue 727

- aria-practices.html
- examples/carousel/carousel-1.html
- examples/spinbutton/datepicker-spinbuttons.html
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/1223.html" title="Last updated on Oct 24, 2019, 10:16 PM UTC (1cca615)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1223/7532022...nschonni:1cca615.html" title="Last updated on Oct 24, 2019, 10:16 PM UTC (1cca615)">Diff</a>
> typo: mimimum -> minimum

- .travis.yml
Take the firefox update out of this PR: https://github.com/w3c/aria-practices/pull/1116
> Update firefox in CI to latest

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1252.html" title="Last updated on Nov 8, 2019, 12:44 AM UTC (d8d5e1c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1252/7cb6858...d8d5e1c.html" title="Last updated on Nov 8, 2019, 12:44 AM UTC (d8d5e1c)">Diff</a>
> Appendix sections: Fix indentation level in HTML source

- .eslintrc.json
- examples/combobox/aria1.1pattern/js/grid-combobox.js
Not sure if this is the right solution, or just silencing something that might be a bug
> fix: enable eslint no-fallthrough

- .eslintrc.json
- aria-practices.html
- examples/combobox/aria1.1pattern/js/grid-combobox.js
- examples/listbox/css/listbox.css
- examples/listbox/js/listbox.js
- examples/listbox/listbox-collapsible.html
- examples/listbox/listbox-grouped.html
- examples/listbox/listbox-rearrangeable.html
- respec-config.js
- test/tests/listbox_collapsible.js
- test/tests/listbox_grouped.js
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1256.html" title="Last updated on Nov 11, 2019, 4:03 AM UTC (6ab8f46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1256/988d6a4...6ab8f46.html" title="Last updated on Nov 11, 2019, 4:03 AM UTC (6ab8f46)">Diff</a>
> Update apg-1.2 from master

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1257.html" title="Last updated on Nov 11, 2019, 4:56 AM UTC (8bde70a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1257/b3ce233...8bde70a.html" title="Last updated on Nov 11, 2019, 4:56 AM UTC (8bde70a)">Diff</a>
> Add change log for APG 1.2 Working Draft 3 to APG 1.2 branch

- aria-practices.html
Closes #1289
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1292.html" title="Last updated on Jan 23, 2020, 6:31 AM UTC (3620b98)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1292/d75c28b...3620b98.html" title="Last updated on Jan 23, 2020, 6:31 AM UTC (3620b98)">Diff</a>
> Name and Description Guidance Section: Fix capitalization typo

- examples/dialog-modal/js/calendar-button.js
- examples/dialog-modal/js/datepicker-day.js
- examples/dialog-modal/js/datepicker.js
Resolves #1311 
[View the example in the compare branch of this pull request](https://raw.githack.com/w3c/aria-practices/1311-datepicker-keydown/examples/dialog-modal/datepicker-dialog.html)
> Date Picker Dialog: Remove mixed click and enter/space listeners for buttons

- package-lock.json
- package.json
This is #1310 on top of latest master, and `package-lock.json` generated from `npm install --package-lock-only`
> #1310 rebased (Update lint-staged to the latest version 🚀)

- coverage/index.html
- coverage/prop-coverage.csv
- examples/index.html
Run of coverage-reports.js and reference-tables.js to update files.
> Infrastructure: Update reference indexes and coverage reports

- package-lock.json
- package.json
- Moved npm-merge-driver to devDependency
- Updated all packages
- Deleted lockfile and regenerated
> chore: Updated NPM deps

- examples/combobox/combobox-select-only.html
@carmacleod 
Thank you for #1432. Here is an idea for wording it to present the divergence as part of the accessibility features of the example. I'm not sure if I have the description of how mouse users cancel quite right.
Just an idea ... incorporate as you think best.
> PR1432 alternative wording

- examples/dialog-modal/datepicker-dialog.html
> typo: enableing -> enabling

- .vnurc
- package.json
Removed the HTML validation suppression only related to that file
> chore: Stop linting Deleted Section Archive

- examples/toolbar/toolbar.html
- test/tests/toolbar_toolbar.js
Add remaining missing toolbar tests! :)
> Add remaining missing keyboard tests

- .eslintrc.json
- .gitignore
- cspell.json
- package-lock.json
- package.json
- scripts/coverage-report.js
- scripts/create-gh-project.js
- scripts/reference-tables.js
This script allows you to create a new GH project (if you have permission for this repo, and create a GH token and put it in a `.env` file)!
It reuse the logic and a lot of the code that @mfairchild365 wrote for the aria-at project here: https://github.com/w3c/aria-at/issues/126
> Add script to create new GH project

- .github/dependabot.yml
This seems to be the pattern used currently
> Infrastructure: Update Dependabot commit message

- .stylelintrc
- examples/carousel/css/carousel-prev-next.css
- examples/carousel/css/carousel-tablist.css
- examples/combobox/css/combobox-datepicker.css
- examples/menubar/css/menubar-editor.css
- examples/menubar/css/menubar-navigation.css
https://stylelint.io/user-guide/rules/no-descending-specificity
Fixes #1522
> chore: Stylelint no-descending-specificity

- .vnurc
- examples/landmarks/form.html
- examples/radio/radio-activedescendant.html
- examples/radio/radio.html
- package.json
Few of the other warnings were going to be noisier changes with in-flight PRs, so left them disabled for now
> Infrastructure: Check vnu-jar warnings in addition to errors

- aria-practices.html
- examples/slider/slider-color-viewer.html
- examples/spinbutton/datepicker-spinbuttons.html
- examples/toolbar/toolbar.html
Fixes #1900
Changes increment and descrement to increase and decrease to be more human (and not programmer) friendly. Did not change comments in js files as those seem appropriate.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1901.html" title="Last updated on May 10, 2021, 11:02 PM UTC (0833136)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1901/276fed3...0833136.html" title="Last updated on May 10, 2021, 11:02 PM UTC (0833136)">Diff</a>
> Terminology Inconsitencies

- examples/spinbutton/js/datepicker-spinbuttons.js
- test/tests/spinbutton_datepicker.js
> typo: fourteen -> fourteenth

- examples/switch/switch-button.html
Just a minor issue with the new linting being turned on, and another PR landing ealier
> Switch Example using HTML Button: Replace SingleQuotes with Doublequotes for attribute values

- examples/combobox/combobox-autocomplete-both.html
- examples/combobox/combobox-autocomplete-list.html
- examples/combobox/combobox-autocomplete-none.html
Addresses the current CI failure on main branch
> Combobox examples with list popups: Fix missing closing LI in accessibility features section

- .github/workflows/coverage-report.yml
Closes #2045
Addresses the breaking changes in the new octokit library https://github.com/actions/github-script#breaking-changes-in-v5
> Infrastructure: Update for github-script@v5

- .husky/_/husky.sh
- package-lock.json
- package.json
Includes a large diff in the package-lock.json to remove an unrelated issue to some old `resolved: false` entries that were only fixable by removing and recreating the lock file.
> Infrastructure: Update Husky v7 and script changes

- test/tests/menu-button_links.js
> Infrastructure: Comment out a test in menu-button_links.js

- .github/workflows/vnu-jar-problem-matcher.json
Currently the "info" at the start breaks the problem matcher, so these
aren't shown on PRs
> Infrastructure: vnu-jar problem matcher update

- aria-practices.html
- respec-config.js
* Changes to the currently supported respec profile
* Updates to use group syntax in respec config
* Updates mailing list to public-aria-practices
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2127.html" title="Last updated on Nov 14, 2021, 4:54 AM UTC (6a2c565)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2127/edddf9f...6a2c565.html" title="Last updated on Nov 14, 2021, 4:54 AM UTC (6a2c565)">Diff</a>
> Infrastructure: Update Respec Profile

- package-lock.json
- package.json
> Infrastructure: remove npm-merge-driver and update to lockfileVersion: 2

- aria-practices.html
- examples/feed/feedDisplay.html
- examples/index.html
- examples/listbox/listbox-collapsible.html
- examples/listbox/listbox-rearrangeable.html
- examples/listbox/listbox-scrollable.html
- examples/radio/css/radio-rating.css
- examples/radio/js/radio-rating.js
- examples/radio/radio-activedescendant.html
- examples/radio/radio-rating.html
- examples/radio/radio.html
- examples/slider/slider-rating.html
- examples/switch/css/switch-checkbox.css
- package-lock.json
- package.json
- respec-config.js
- test/tests/radio_radio-rating.js
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2134.html" title="Last updated on Nov 14, 2021, 4:28 PM UTC (c064123)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2134/bb86e73...c064123.html" title="Last updated on Nov 14, 2021, 4:28 PM UTC (c064123)">Diff</a>
> Update 1.2 publication branch with latest content from main

- aria-practices.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2146.html" title="Last updated on Nov 15, 2021, 11:56 PM UTC (825e7ee)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2146/f9441af...825e7ee.html" title="Last updated on Nov 15, 2021, 11:56 PM UTC (825e7ee)">Diff</a>
> Appendix: Add final revisions to change log

- aria-practices.html
* Add jumpto menu to change log
* Revise order of changes in log for readability
* Removes mention of 1.1 version from intro to acknowledgements
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2148.html" title="Last updated on Nov 16, 2021, 6:38 PM UTC (9e5f9a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2148/e27c36a...9e5f9a8.html" title="Last updated on Nov 16, 2021, 6:38 PM UTC (9e5f9a8)">Diff</a>
> Appendix: Revise change log and unversion acknowledgements

- examples/carousel/css/carousel-prev-next.css
- examples/carousel/css/carousel-tablist.css
- examples/grid/css/dataGrids.css
- examples/listbox/css/listbox.css
- examples/slider/css/slider-color-viewer.css
- examples/slider/css/slider-multithumb.css
- examples/switch/css/switch-checkbox.css
- package-lock.json
- package.json
This was changed during the last major version, but it looks like they moved back from the precentage format quickly
> Infrastructure: Update stylelint for opacity changes

- aria-practices.html
Fixes #2173
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2174.html" title="Last updated on Dec 18, 2021, 1:37 AM UTC (1899990)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2174/3dd5a2d...1899990.html" title="Last updated on Dec 18, 2021, 1:37 AM UTC (1899990)">Diff</a>
> Typo, change effected to affected

- examples/js/notice.html
added correct directory structure to fix broken links
> fixed the broken links in Important Note about Use of This example

- .github/workflows/wai-trigger-cleanup.yml
- .github/workflows/wai-trigger-deploy.yml
- .github/workflows/wai-trigger-pr.yml
* Ignore dependabot branches for PR update and cleanup workflows
* Rename workflows related to WAI-APG site deploy for consistency
___
[WAI Preview Link](https://deploy-preview-19--wai-aria-practices2.netlify.app)
> Infrastructure: Update WAI-APG site resources

- index.html
This PR includes minor revisions to home page text. It serves as an initial test of the process for updating the home page of the new WAI-APG site.
___
[WAI Preview Link](https://deploy-preview-51--wai-aria-practices2.netlify.app)
> Home Page: Revise intro text

- index.html
Test to check impact of removing some of the content that follows each of the H2 elements.
___
[WAI Preview Link](https://deploy-preview-57--wai-aria-practices2.netlify.app)
> Home page: Test removing some taglines

- examples/checkbox/checkbox.html
- examples/dialog-modal/datepicker-dialog.html
- examples/dialog-modal/js/datepicker-dialog.js
- examples/index.html
Resolves #2285
___
[WAI Preview Link](https://deploy-preview-38--wai-aria-practices2.netlify.app)
> Checkbox and Date Picker Dialog Examples: Editorial change to roles states and properties table markup

- .eslintignore
- cspell.json
- examples/js/skipto.js
This PR resolves #2387, which fixes the build script in wai-aria-practices.
> Copy skipto.js from wai-aria-practices to aria-practices

- aria-practices.html
@mcking65 @alflennik @s3ththompson I create the new PR. I hope it can make it to the publication schedule this Thursday. 
___
[WAI Preview Link](https://deploy-preview-161--wai-aria-practices2.netlify.app)
> Acknowledgements: Add Carolyn MacLeod as honorary editor

- .github/workflows/wai-trigger-deploy.yml
- .github/workflows/wai-trigger-pr.yml
- content/apg-home.html
Fixes preview links, including support for fork-based PRs.
___
[WAI Preview Link](https://deploy-preview-178--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 12 Dec 2022 18:29:34 GMT)._
> Infrastructure: Fix previews by changing file paths and globs in build workflow

- package.json
Accounting for the new paths the pattern example files are now located.
> Infrastructure: Update lint-staged examples path

- .github/workflows/wai-trigger-cleanup.yml
Update `actions/setup-node@v2` usage to `actions/setup-node@v3`
> Infrastructure: Update actions/setup-node@v2 to v3

- content/practices/read-me-first/read-me-first-practice.html
As per consensus of the 2023-04-25 meeting of the ARIA Authoring Practices Task Force:
https://www.w3.org/2023/04/25-aria-apg-minutes.html
___
[WAI Preview Link](https://deploy-preview-218--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 27 Apr 2023 16:37:55 GMT)._
> Read Me First: Remove reference to Internet Explorer in browser support section

- content/patterns/grid/examples/layout-grids.html
___
[WAI Preview Link](https://deploy-preview-226--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 08 Jun 2023 15:35:52 GMT)._
> Layout Grids Example 3 - Scrollable Search Results: Update example content to replace an obsolete link

- content/patterns/dialog-modal/examples/dialog.html
- content/patterns/menu-button/examples/menu-button-links.html
- content/patterns/slider/examples/slider-color-viewer.html
Adds AT support tables for three examples:
* Color viewer slider
* Modal dialog
* Navigation menu button
* [Preview color viewer slider support table](https://deploy-preview-237--aria-practices.netlify.app/aria/apg/patterns/slider/examples/slider-color-viewer/)
* [Preview modal dialog support table](https://deploy-preview-237--aria-practices.netlify.app/aria/apg/patterns/dialog-modal/examples/dialog/)
* [Preview navigation menu button support table](https://deploy-preview-237--aria-practices.netlify.app/aria/apg/patterns/menu-button/examples/menu-button-links/)
* N/A: [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process …
> Add AT Support tables for modal dialog, 1 slider, and navigation menu button

- content/patterns/landmarks/examples/css/common.css
resolves #2384
* N/A: [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by reviewer_id
* N/A: [Test review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#test_review) by reviewer_id
___
[WAI Preview Link](https://deploy-preview-239--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 27 Jun 2023 18:34:49 GMT)._
> Landmark Example Pages: remove background colours that cause color contrast failures

- content/about/acknowledgements/acknowledgements.html
___
[WAI Preview Link](https://deploy-preview-365--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 14 Oct 2024 09:52:31 GMT)._
> Acknowledgements Page: Update W3C Staff Editors

- cspell.json
- package-lock.json
- package.json
> Infrastructure: Bump cspell to 8.17.1 and ignore "Renée"

- content/patterns/slider-multithumb/examples/js/slider-multithumb.js
Closes #3174
___
[WAI Preview Link](https://deploy-preview-381--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 15 Jan 2025 22:00:35 GMT)._
> Multi-thumb Slider Example: Fix glitch that cut off part of ring on hover

- content/patterns/treegrid/examples/css/treegrid-1.css
- package-lock.json
- package.json
Looks like there was a minor formatting change in the bump that was failing in #3233, so I splitt this out with the auto-fix
___
[WAI Preview Link](https://deploy-preview-386--aria-practices.netlify.app/ARIA/apg) _(Last built on Sat, 01 Mar 2025 21:14:28 GMT)._
> Infrastructure: Bump Prettier 3.5.2

- content/practices/landmark-regions/landmark-regions-practice.html
___
[WAI Preview Link](https://deploy-preview-349--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 19 Dec 2024 16:29:22 GMT)._
> Fix typo in landmark-regions-practice.html Region
