w3c/aria-practices

aria-practices.html

Paragraph previously duplicated reference to `aria-valuemin` where `aria-valuemax` was intended.

Clarify role names in § 3.1.6.1

---

README.md
bin/generate

- Use this script from the command line to copy the template.
- This can get more sophisticated over time, or replaced with a more
robust template generator. For now, it captures in code what would
otherwise be undocumented or documented poorly in the README.
```
aria-practices % ls examples
alert           button          checkbox        coding-template css      js              link            radio           slider
aria-practices % bin/generate date-picker
aria-practices % head -10 examples/date-picker/date-picker.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>ARIA Example: Pattern Name: Coding Example Name</title>
<meta name="generator" content="BBEdit 10.5" />
<link href="../css/core.css" rel="stylesheet">
<link href="../css/table.css" rel="stylesheet"> …
```

Define a shell script to generate new examples.

---

examples/breadcrumb/index.html

Fix issues in https://github.com/w3c/aria-practices/issues/187. Please squash the commits in this PR.

Breadcrumb

---

examples/button/button.html

Just added information about why tabindex=0 is needed on the A element in this case

Updated button example documentation

---

examples/link/css/link.css
examples/link/link.html

Fixes issue described in https://github.com/w3c/aria-practices/issues/228#issuecomment-278679852.
Tested in: 
- Safari 10 on macOS 10.12
- Edge on Windows 10
- IE 11 on Windows 10
- Firefox 50 on Windows 10
All tests on Windows include a check in High Contrast mode.

Remove example 4, add clearer focus outline

---

examples/breadcrumb/css/breadcrumb.css
examples/breadcrumb/index.html

- Separators now added as CSS style rather than a HTML entity.
- Added explanation text on example page.

Separators are no longer announced by SRs

---

examples/listbox/js/listbox.js

After a select item is toggled, attribute aria-disabled on this.deleteButton was always set. This results in an error if no deleteButton is set.

Check for this.deleteButton before trying to set an attribute

---

examples/grid/js/dataGrid.js

Before moving the focus in the grid, make sure that the focused item is set properly. If the focused item was changed because of the reading cursor, reset the focusedRow and focusedCol before navigating further.

Move focus with reading cursor

---

examples/listbox/css/listbox.css
examples/listbox/js/listbox.js
examples/listbox/js/main.js
examples/listbox/listbox.html

Listboxes with more options than their height or max-height can accomodate, lack visual scrolling when keyboard navigation is used. I've written a few lines of js to fix this and included an example with notes to demonstrate it.

Support for scrolling in listboxes

---

examples/css/core.css

In the example documents added grid lines for the Role, Property, State, and Tabindex Attributes Tables

Added Grid Lines for the Role, Property, State, and Tabindex Attributes Tables

---

examples/grid/js/menuButton.js

Fixed menu buttons on data grid example page so that they do not autofocus on page load

Do not focus on menu buttons on page load

---

aria-practices.html

For issue #336, modified keyboard interaction subsection of menu or menubar design pattern section in aria-practices.html:
1. Mark space bar toggle of menuitemcheckbox as optional.
2. Mark space bar toggle of menuitemradio as optional.
3. Add optional up arrow behavior for menuitem elements in a menubar. (Note, this behavior is implemented in the examples).

Menu Design Pattern: Document Optional Behaviors for Space and Up Arrow

---

examples/disclosure/js/disclosureButton.js

I fixed a bug of the Javascript adding a tabindex=0, this is not needed since the button is already part of the tab order of the page

removed from Javascript setting a tabindex=0

---

examples/landmarks/at.html

The typo was causing the labelledby to point at the wrong/missing ID

chore: typo in "nvda" aria-labelledby value

---

examples/menubar/menubar-1/js/MenubarItemLinks.js
examples/menubar/menubar-1/js/MenubarLinks.js
examples/menubar/menubar-1/js/PopupMenuItemLinks.js
examples/menubar/menubar-1/js/PopupMenuLinks.js
examples/menubar/menubar-1/menubar-1.html

This bug fixes a problem in the source code view and I don't think we needed a label for the role=menu or a tabindex=-1 on the menu role

Navigation Menubar Example: Remove second example with dynamically added ARIA attributes

---

examples/accordion/accordion.html
examples/accordion/css/accordion.css
examples/accordion/js/accordion.js

This commit addresses issues #424 and #425.
Note: I needed `data-allow-multiple` to also mean `data-allow-toggle` otherwise you could end up in a situation where you can open all accordions but not close them.

Accordion fixes

---

examples/accordion/js/accordion.js

Fix for issue #455 by managing `aria-disabled` state on Accordion triggers when toggling is not allowed.

Add aria-disabled to Accordion

---

examples/listbox/js/listbox-rearrangeable.js
examples/listbox/js/listbox.js
examples/listbox/listbox-rearrangeable.html

- Updated Add and Important buttons to be triggered by Enter instead of Delete
- Added Alt up/down shortcuts for shifting items in Important list

Update keyboard shortcuts for listbox

---

README.md

The wiki's Design Pattern Status page [was renamed earlier this year](https://github.com/w3c/aria-practices/wiki/_compare/31351016c6648aab547a44c308af902abb370126...470bff08a79cdc691539174fbcee2cd62e14f9db).
This PR updates the README's link to that wiki page.

Update pattern status link in README.md

---

examples/checkbox/checkbox-2/js/checkboxMixed.js

Fix issue #486.
The selected state of each individual checkbox was only recorded on click of that individual checkbox. In order to properly track the state of all the checkboxes a routine is added to update the state of all controlled checkboxes when the master is set to mixed state, which happens every time a change occurs in the controlled checkboxes.
I would have preferred a cleaner approach where the controller stored the mixed states, but did not want to be too destructive with my changes.
cc: @mcking65

Fix issue 486: Update mixed state on change

---

examples/accordion/accordion.html
examples/accordion/css/accordion.css

Based on a [comment](https://github.com/w3c/aria-practices/issues/401#issuecomment-338934277) by @finalborgo I have fixed 2 CSS bugs for MS Edge.
The first is an issue with using `pointer-events: none` on non-block level elements will still allow interaction. See MS Edge defect [8295099](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8295099/).
The second, Edge has an issue with using the `hidden` attribute. See MS Edge defect [4806035](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/4806035/)
Those are really sad bugs IMO. I can understand why this project doesn't necessarily support Edge. Thankfully, there were simple CSS workarounds.
Lastly, just to be complete, I added `type="button" to all the accordion trigger buttons, as a best practice …

[Accordion] Fix CSS bugs in MS Edge

---

aria-practices.html
examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
examples/combobox/aria1.0pattern/combobox-autocomplete-none.html
examples/combobox/aria1.0pattern/css/combobox-1.0.css
examples/combobox/aria1.0pattern/css/listbox.css
examples/combobox/aria1.0pattern/js/combobox-1.0-list.js
examples/combobox/aria1.0pattern/js/combobox-1.0-listbox.js
examples/combobox/aria1.0pattern/js/combobox-1.0.js
examples/combobox/aria1.0pattern/js/listbox.js
examples/combobox/aria1.0pattern/js/listboxOption.js
examples/combobox/aria1.1pattern/grid-combo.html
examples/combobox/aria1.1pattern/listbox-combo.html

For issue #99, integrate contributions from @jongund and @mcking65 on three ARIA 1.0 style combobox examples.
Each example demonstrates a different type of autocomplete:
* List with manual selection
* List with inline autocomplete
* No autocomplete.
This includes updates to the links from the design pattern as well as updates to links from the ARIA 1.1 combobox example pages.

ARIA 1.0 Combobox Examples: Integrate 3 New Examples

---

examples/treeview/treeview-2/treeview-2b.html

Fixed typo in an example's title tag.

---

aria-practices.html

Minor editorial revisions to intro

---

examples/grid/js/layoutGrids.js

Fix #531 issue with NUX instructions not closing as expected with IE11.
A loop was created on focus, where the instructions where displayed and then dismissing the instructions set focus to the element that displayed the instructions on focus. This happened because the `once` option was used for the event listener, which is not supported in IE11.
Created an event listener that, when fired, removed the event listener and setup the instructions and close listeners/ handlers.
Tested with IE11 on Win7 and Win8, as well as Chrome/ Safari/ Firefox on Safari.

Fix Grid Layout Instructions

---

examples/radio/radio-1/radio-1.html

I noticed some grammar errors in this example and tried to correct them. The indentation of code was also fixed.
When I find the time, I try to have a more focused look at the example (and potentially others) and see whether they need any care.

Radio Group with Roving tabindex Example: Clean up example HTML and correct supporting documentation

---

aria-practices.html
examples/listbox/listbox-collapsible.html
examples/listbox/listbox-rearrangeable.html
examples/listbox/listbox-scrollable.html

Fixes a minor text error I encountered while reading the modified files. The text "withthe" should be "with the".
Hope you don't mind the patch. Love the site and work, very helpful!

Correct text error "withthe" should be "with the"

---

aria-practices.html

The "wrapping from the last to the first" text is the same for both the right and left arrow instructions. It seems more clear to specify "first to last" when using the left arrow.

Clarify wrap direction when using left arrow

---

.eslintignore
package.json
respec-config.js

Just noticed that the globbing that ESLint wasn't catching everything. There is already a `.eslintigore` file to exclude third party files that should be excluded.
Ran the `fix` target to apply the formatting after extending the glob pattern.

chore: Update ESLint task globbing and autofix

---

examples/button/button.html
examples/button/css/button.css
examples/css/core.css

*In preparation for developing examples for tri-state toggle buttons (see issue #535).*
This pull request addresses/changes the following:
- Fixes indentation issues in the markup
- Removing `type="text/javascript"` (some scripts have it, some don’t. I chose one.)
- Removed `/` in the meta charset tag (some examples have it, some don’t).
Please note: Due to indentation changes, the GitHub diff doesn’t show some changes. For example,I changed `<th>` to `<td>` elements when inside `<tbody>`. It may have been incorrect to do so.

Clean up button example code

---

.travis.yml
.vnurc
package-lock.json
package.json

From the README:
> All HTML should validate in the NU HTML Validator. Exceptions to this rule are warnings and errors related to future ARIA features we need to implement.
Current errors are below, but may be related to current work
```console
"file:examples/landmarks/at.html":93.18-93.119: error: Bad value “80%” for attribute “width” on element “img”: Expected a digit but saw “%” instead.
"file:examples/landmarks/at.html":126.20-126.121: error: Bad value “80%” for attribute “width” on element “img”: Expected a digit but saw “%” instead.
"file:examples/landmarks/at.html":187.16-187.115: error: Bad value “80%” for attribute “width” on element “img”: Expected a digit but saw “%” instead.
"file:examples/landmarks/at.html":97.13-97.44: error: The “aria-labelledby” attribute must point to an …
```

chore: add VNU checking

---

aria-practices.html

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/687.html" title="Last updated on Jun 15, 2018, 5:02 PM GMT (d8b9b4e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/687/a84d4d3...d8b9b4e.html" title="Last updated on Jun 15, 2018, 5:02 PM GMT (d8b9b4e)">Diff</a>

Landmark Regions: Fix labeling requirement issue #453

---

aria-practices.html
respec-config.js

Changed version numbers for v1.2. 
Removed Changelog
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/719.html" title="Last updated on Jun 18, 2018, 8:51 PM GMT (3c276fb)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/719/c555c83...3c276fb.html" title="Last updated on Jun 18, 2018, 8:51 PM GMT (3c276fb)">Diff</a>

Initial Changes for v1.2

---

aria-practices.html
examples/button/button_idl.html
examples/button/js/button_idl.js

Fix #701
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/718.html" title="Last updated on Jun 15, 2018, 9:29 PM GMT (c430691)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/718/30a96f0...c430691.html" title="Last updated on Jun 15, 2018, 9:29 PM GMT (c430691)">Diff</a>

Add IDL example for button for ARIA 1.2

---

aria-practices.html

This fixes a typo in section [3.8 Dialog (Modal)](http://w3c.github.io/aria-practices/#dialog_modal).

Fix typo: overlayed/overlaid

---

aria-practices.html

Fix #700 by adding structural section
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/720.html" title="Last updated on Jun 15, 2018, 10:34 PM GMT (f28fb46)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/720/c555c83...f28fb46.html" title="Last updated on Jun 15, 2018, 10:34 PM GMT (f28fb46)">Diff</a>

Initial Version for #700

---

aria-practices.html

Fix for #602. Please review
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/683.html" title="Last updated on Jun 14, 2018, 10:20 PM GMT (8c19170)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/683/398d711...8c19170.html" title="Last updated on Jun 14, 2018, 10:20 PM GMT (8c19170)">Diff</a>

Tabs Pattern: Clarify where focus should go when deleting tabs to fix issue 602

---

examples/menu-button/js/Menubutton2.js

For the menu button links example, currently, with the menu expanded, clicking the button trigger does not cause the menu to collapse. It does, however, do this in the menu button actions example, and I think this is the correct behavior, especially since, without that, this means, on touch devices, there is essentially no intuitive way of collapsing the menu. The issue appears to be that line 111 of Menubutton2.js is not passed the true boolean argument, as it is on Menubutton.js. I've fixed this and it appears to work now.

For menu button links example, collapse menu when clicking button

---

examples/menubar/menubar-2/js/MenubarItemAction.js
examples/menubar/menubar-2/menubar-2.html

Editor menubar example: Make Escape close submenu when focus in menubar

---

examples/dialog-modal/alertdialog.html
examples/dialog-modal/dialog.html

Fixes #738.
The dialog example was missing the app.js script (874b4cf081f9e884ea8bfbacf201eb8ee11d16d6), and was using the wrong semantics for the code snippet (ca3206c308289707c7e722e12f1ef1bf75a1734f).
In light of this, I looked through all of the other `examples/**/*.html` files to make sure there weren't any similar errors. I wasn't able to find any other issues other than a missing linebreak in my alertdialog example (560c3e360fc74425b002b7d3d4659b01c63cbfa5).

Modal Dialog Example: Fix HTML source display highlighting

---

examples/menu-button/css/MenubuttonLinks.css
examples/menu-button/js/MenuItemLinks.js
examples/menu-button/js/PopupMenuLinks.js

Issue #396: Fixes the unreachable code problem
Issue #588: Fixes shift-tab not closing the menu
Updated CSS focus styling
[Navigation menu button example in Jon's fork](https://rawgit.com/jongund/aria-practices/issues-396-588-menubutton/examples/menu-button/menu-button-links.html)

Navigation Menu Button Example: fix unreachable code and shift-tab not closing menu

---

examples/combobox/aria1.0pattern/js/combobox-1.0-list.js

For issue #559, fix the escape key behavior so that it will clear the textbox.

ARIA 1.0 Combobox Example: Make escape clear textbox

---

aria-practices.html
common/terms.html
examples/listbox/listbox-collapsible.html
examples/menu-button/js/Menubutton2.js
examples/menubar/menubar-2/js/MenubarItemAction.js
examples/menubar/menubar-2/menubar-2.html
examples/radio/css/radio.css
examples/treeview/treeview-1/css/tree.css
examples/treeview/treeview-2/css/treeLinks.css

For issue #603, modified: examples/menubar/menubar-2/menubar-2.html.
In the accessibility features section, added items 4 and 5 describing the conditions when mouse hover can move focus.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/711.html" title="Last updated on Jun 27, 2018, 7:07 AM GMT (2d297b6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/711/c555c83...2d297b6.html" title="Last updated on Jun 27, 2018, 7:07 AM GMT (2d297b6)">Diff</a>

Editor Menubar Example: Add notes about hover and focus movement

---

.travis.yml

A link/link.js tests failed when running on travis CI:
https://travis-ci.org/w3c/aria-practices/builds/396923884#L6
I could reproduce the bug by:
- Running with Firefox with 56.0.2
- Making sure the element appears below the fold
It does not appear when I run locally with 60.0.2 -- it appears there is a bug with firefox 56.0.2 not scrolling the element into view before sending a key!

Update firefox on travis CI 

---

examples/combobox/aria1.1pattern/grid-combo.html
examples/combobox/aria1.1pattern/listbox-combo.html

ARIA 1.1 Combobox Examples: Use `for` attribute on label element instead of aria-labelledby on `input` element 

---

examples/spinbutton/js/spinbutton.js
examples/spinbutton/spinbutton.html

This is the initial commit for the Spinbutton issue #125, very much a work in progress.
Testing without AT (VoiceOver/ Safari), UP/DOWN will increment/ decrement as designed. With AT, VoiceOver suggests different keys for operation. I am looking for advice on how to proceed.
With VO, CTRL+OPTION+UP/DOWN is required to increment/ decrement the counter. CTRL+OPTION is not firing, so while VO is announcing the change I am not capturing any events to respond to.
cc: @mcking65

Spinbutton - Initial commit, work in progress

---

examples/link/link.html
test/index.js
test/tests/link.js
test/util/start-geckodriver.js

Fix testnames based on @sh0ji 's suggestions and fix one small comment.
I left the ariaTest abstraction for now (including the check for data-test-id) -- we can revisit it later. I did change the "t.is" in ariaTest to an assert in order to not effect the test count for test planning.

link/link.js feedback - minor fixes

---

aria-practices.html

A note to the Listbox pattern discusses `aria-activedescendant`, and incorrectly referred to `treeitem` role, probably due to copy/paste error from a identical note to the [Tree View pattern](https://w3c.github.io/aria-practices/#TreeView), whereas [`listbox` uses the `option` role for its items](https://w3c.github.io/aria/#listbox).
***
<a href="https://pr-preview.s3.amazonaws.com/dusek/aria-practices/pull/771.html" title="Last updated on Jul 15, 2018, 11:18 AM GMT (94f95e5)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/771/ca1f155...dusek:94f95e5.html" title="Last updated on Jul 15, 2018, 11:18 AM GMT (94f95e5)">Diff</a>

Fix Listbox to refer to `option` role when discussing `aria-activedescentant`

---

examples/menubar/menubar-2/menubar-2.html

Hi @mcking65 -- Caught some more duplicate data-test-id attributes (role="menuitem" elements can be found in menubar or submenu), this PR deduplicates.

Updates to menubar-2.html data-test-id

---

test/tests/listbox-combo.js
test/util/assertAriaSelectedAndActivedescendant.js

When noticing #813 in the example `listbox/listbox-scrollable.html` example, I realized that setting the "aria-selected" attribute on the appropriate option is not strictly a part of the aria-activedescendant pattern. I renamed this util function to specify that it is checking for both the aria-activedescendant pattern and a corresponding aria-selected attribution.

Updates to aria-activedescendant util function

---

examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
examples/combobox/aria1.1pattern/listbox-combo.html
test/tests/combobox-autocomplete-both.js
test/tests/listbox-combo.js
test/util/assertAttributeDNE.js

This commit adds all tests for example: combobox/aria1.0pattern/combobox-autocomplete-both.html
It also adds a few missing tests and updates some test logic in: combobox/aria1.1pattern/listbox-combo.html
Ready for review, @mcking65 -- but I'll be out of the office until August 14th, so will not be able to address until then!

Add tests for combobox-autocomplete-both.js, update listbox-combo.js

---

examples/listbox/css/listbox.css
examples/listbox/js/listbox.js

For issue #794, update aria-selected for single-selection listbox options on focus change in listbox/js/listbox.js:
* When not multi-selection, toggling aria-selected when option receives or loses focus.

Single-selection listbox example: Fix aria-selected bug

---

.vnurc
package-lock.json
package.json

Realized that the original wasn't catching all subfolders. Fixed up the issues that I understood, but there are a few combobox examples using `rel` on `ul` and `li` elements that I don't understand enough to fix. EX: 
```
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":57.11-57.63: error: Attribute “rel” not allowed on element “ul” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":67.13-67.77: error: Attribute “rel” not allowed on element “li” at this point.
"file:/Users/nschonni/Documents/github/aria-practices/examples/menubar/menubar-2/menubar-2.html":68.13-68.79: error: Attribute “rel” not allowed on element “li” at this point. …
```

Expand VNU validator file pattern

---

examples/coding-template/Example-Template.html
examples/combobox/aria1.0pattern/combobox-autocomplete-both.html
examples/combobox/aria1.0pattern/combobox-autocomplete-list.html
examples/combobox/aria1.0pattern/combobox-autocomplete-none.html
examples/combobox/aria1.1pattern/listbox-combo.html
examples/disclosure/disclosure-faq.html
examples/disclosure/disclosure-img-long-description.html
examples/feed/feed.html
examples/menubar/menubar-1/mb-academics.html
examples/menubar/menubar-1/mb-arts.html
examples/menubar/menubar-1/mb-outreach.html
examples/menubar/menubar-1/mb-research.html
examples/menubar/menubar-1/menubar-1.html
examples/menubar/menubar-2/menubar-2.html
examples/treeview/treeview-1/treeview-1a.html
examples/treeview/treeview-1/treeview-1b.html
examples/treeview/treeview-2/treeview-2a.html
examples/treeview/treeview-2/treeview-2b.html

Ran cspell to fix up some typos. Not entirely done, but I'll try and add it to the build with the config separately

Spelling fixes

---

test/tests/LayoutGrids.js
test/tests/combobox-autocomplete-both.js
test/tests/dialog.js
test/tests/link.js
test/tests/listbox-combo.js
test/tests/listbox-scrollable.js
test/tests/menubar-2.js
test/tests/radio-1.js
test/tests/slider-1.js
test/tests/tabs.js
test/util/assertAriaLabelledby.js
test/util/assertAttributeDNE.js
test/util/assertTabOrder.js

Fix race conditions and clean up code in regression tests

---

test/tests/disclosure-faq.js

Tests written, only blocking on acceptance of race condition PR: #837

Add tests for disclosure/disclosure-faq.html

---

test/tests/toolbar.js

Waiting on questions on toolbar review: https://github.com/w3c/aria-practices/issues/539#issuecomment-413953446
Also blocking on acceptance of race condition PR: #837

WIP: add tests for toolbar/toolbar.html example

---

.travis.yml

Before #851, travis.ci ran "npm test", which runs the linters and the regression tests all in one. Now the tests are separated out and the regression tests needed to be added explicitly back in.
This PR also sets "concurrency=1" for the ava tests. This will element the bug which causes firefox to crash at least once (sometimes twice) during the regression test. We reported the crashing of firefox to geckodriver in this [bug](https://github.com/mozilla/geckodriver/issues/1135#issuecomment-417337821).

Add regression test run to travis CI build stages

---

examples/treeview/treeview-2/treeview-2b.html

The attributes aria-level and aria-posinset were incorrectly set on on treeitem.
This bug was caught by the tests written here:  #870

Fix bug in exampe: treeview/treeview-2/treeview-2b.html

---

aria-practices-DeletedSectionsArchive.html
aria-practices.html
examples/dialog-modal/dialog.html
examples/listbox/listbox-collapsible.html

Just ran Vale to find duplicate words. There were a few others, but they seemed intentional
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/867.html" title="Last updated on Aug 30, 2018, 5:35 AM GMT (48966e8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/867/1379511...nschonni:48966e8.html" title="Last updated on Aug 30, 2018, 5:35 AM GMT (48966e8)">Diff</a>

typos: Double words

---

test/tests/LayoutGrids.js

The bug: I left out some "awaits" before an async function, then checked whether the return value was "truthy" -- so, the tests always passed because a promise is truthy.
This PR adds "await" and changes the test from "truthy" to "true".
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/aria-practices/pull/875.html" title="Last updated on Sep 4, 2018, 5:57 PM GMT (11ecc1e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/875/b601da0...bocoup:11ecc1e.html" title="Last updated on Sep 4, 2018, 5:57 PM GMT (11ecc1e)">Diff</a>

Minor bug in LayoutGrid regression tests

---

.travis.yml
test/index.js
test/tests/LayoutGrids.js
test/tests/button.js
test/tests/checkbox-1.js
test/tests/combobox-autocomplete-both.js
test/tests/combobox-autocomplete-list.js
test/tests/combobox-autocomplete-none.js
test/tests/dialog.js
test/tests/disclosure-faq.js
test/tests/grid-combo.js
test/tests/link.js
test/tests/listbox-combo.js
test/tests/listbox-scrollable.js
test/tests/menubar-2.js
test/tests/tabs.js
test/tests/toolbar.js
test/tests/treegrid-1.js~
test/tests/treeview-1a.js
test/tests/treeview-2a.js
test/tests/treeview-2b.js

I was reviewing some old code and found a few things to fix:
- add useful timeout error messages to all "wait" calls (waiting for state to change after sending interaction to browser)
- use "t.context.url" (set during test set up) instead of getting the url from the browsers
- while testing I found I could regularly locally reproduce some race conditions in the combobox tests, so I fixed those as well

Regression test: expanded error messages, rare race condition fixes

---

examples/grid/dataGrids.html
examples/listbox/listbox-collapsible.html
examples/menu-button/menu-button-links.html
examples/slider/slider-2.html
examples/tabs/tabs-2/tabs.html

@mcking65, please review and merge when convenient :)

Add data-test-id to example pages for regression

---

examples/disclosure/disclosure-img-long-description.html
examples/feed/feed.html
examples/listbox/listbox-rearrangeable.html
examples/menu-button/menu-button-actions-active-descendant.html
examples/menubar/menubar-1/menubar-1.html
examples/slider/multithumb-slider.html

Add data-test-ids to:
- [multithumb-slider](https://w3c.github.io/aria-practices/examples/slider/multithumb-slider.html)
- [menubar-1](https://w3c.github.io/aria-practices/examples/menubar/menubar-1/menubar-1.html)
- [feed](https://w3c.github.io/aria-practices/examples/feed/feed.html)
- [disclosure-img-long-description](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-img-long-description.html)
- [listbox-rearrangeable](https://w3c.github.io/aria-practices/examples/listbox/listbox-rearrangeable.html)
- [menu-button-actions-active-descendant](https://w3c.github.io/aria-practices/examples/menu-button/menu-button-actions-active-descendant.html)

Add data-test-id attribute to remaining examples

---

test/tests/treegrid-1.js

This completes all tests for the treegrid example. This is an odd PR, because the only test added is also commented out due to a bug. This is our convention for handling bugs in the examples so far.
You can read about the bug in the open issue on treegrid [here](https://github.com/w3c/aria-practices/issues/790#issuecomment-422079276).

Add remaining test for treegrid/treegrid-1.html

---

test/index.js
test/tests/combobox-autocomplete-both.js
test/tests/grid-combo.js
test/tests/listbox-combo.js
test/tests/toolbar.js
test/tests/treegrid-1.js
test/tests/treeview-2a.js
test/tests/treeview-2b.js

This commit:
- adds the `.failing` option to the ariaTest wrapper around ava's test
- uses `.failing` in all places where failing tests were previously commented out

Use ava '.failing' to skip known failures

---

examples/grid/js/dataGrid.js
examples/js/utils.js

First of all, thank you very much for the existence of this project. It has been the perfect help for me while implementing a grid-like component.
However, while looking at the example JS code for layout grids, I noticed that event listeners were not being cleaned up properly. This resulted in multiple instances of the same listener being attached to an element.
Calling `.bind()` on a function creates a new function each time, so this code doesn't quite do what it looks like:
```js
// Creates a new function with a specific binding, then adds it as a listener.
elem.addEventListener('focus', this.showKeysIndicator.bind(this));
// Creates a new function with a specific binding, then removes it as a listener.
// This does NOT remove the original listener created above. …
```

Grid Examples: Fix event listener cleanup

---

aria-practices.html

For issue #949, modified the radio group pattern section aria-practices.html:
* Divided the keyboard interaction subsection into two subsections: not in toolbar and in toolbar.
* Added interactions for the special case of radios contained in toolbars.
Go to [section 3.16 in the feature branch](https://raw.githack.com/w3c/aria-practices/issue949-radios-in-toolbars/aria-practices.html#radiobutton) to see the changes.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/952.html" title="Last updated on Dec 19, 2018, 4:46 AM UTC (8260814)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/952/a1a8d92...8260814.html" title="Last updated on Dec 19, 2018, 4:46 AM UTC (8260814)">Diff</a>

Radio Group Pattern: Add new keyboard interaction for radios in toolbars

---

aria-practices.html

Adds a design pattern section for carousels to resolve issue #43.
[Carousel pattern in issue43-add-carousel-pattern branch](https://raw.githack.com/w3c/aria-practices/issue43-add-carousel-pattern/aria-practices.html#carousel)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/957.html" title="Last updated on Jan 15, 2019, 12:54 AM UTC (6f2f95e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/957/08e5fe0...6f2f95e.html" title="Last updated on Jan 15, 2019, 12:54 AM UTC (6f2f95e)">Diff</a>

Add carousel pattern

---

.travis.yml

Addresses #992.
This should allow jobs to fail when they match certain criteria, allowing us to make some jobs non-blocking.

Add allow_failures to Travis

---

examples/google/meter.html

Adds example implementation of the meter role, as described in this [draft specification](https://raw.githack.com/w3c/aria/b3aef2c3cf12c0a5d3bdb9098f2c73b7e0d5d860/index.html#meter)

add example for meter

---

test/tests/menubar-1.js

A test was marked as failing and a bug reported for it (https://github.com/w3c/aria-practices/issues/906) -- but that issue was closed with a PR that fixed the bug (https://github.com/w3c/aria-practices/pull/931). The test now passed but it was still marked as "failing", thus the CI errors.
What I'm confused about is why this wasn't caught earlier?
Fixes https://github.com/w3c/aria-practices/issues/1055

Mark previously failing test as passing

---

aria-practices.html

Addresses issues #70 and #74.
[See section 5 - providing accessible names and descriptions in the working branch](https://raw.githack.com/w3c/aria-practices/zcorpan/labelling-describing/aria-practices.html#names_and_descriptions)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/994.html#names_and_descriptions" title="Last updated on Jun 28, 2019, 3:19 PM UTC (af5793c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/994/9fdf312...af5793c.html" title="Last updated on Jun 28, 2019, 3:19 PM UTC (af5793c)">Diff</a>

Guideline for labeling and describing

---

aria-practices.html
common/biblio.js

PR #994 included changes to common/biblio.js that should not have been merged
because that file is maintained outside the aria-practices repository.
The change was addition of a reference to an external site.
This commit removes the common/biblio.js changes and the reference to them.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1059.html" title="Last updated on Jun 28, 2019, 8:04 PM UTC (d1fa8bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1059/745105f...d1fa8bc.html" title="Last updated on Jun 28, 2019, 8:04 PM UTC (d1fa8bc)">Diff</a>

Naming and describing section: Remove bibliography reference

---

aria-practices.html
examples/disclosure/disclosure-img-long-description.html
examples/grid/LayoutGrids.html
examples/toolbar/toolbar.html
examples/treeview/treeview-2/treeview-2a.html
examples/treeview/treeview-2/treeview-2b.html

Pulled the typo fixes from #841 so they can land while that one is waiting
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/1048.html" title="Last updated on Jul 1, 2019, 9:11 AM UTC (2318a83)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1048/bf22075...nschonni:2318a83.html" title="Last updated on Jul 1, 2019, 9:11 AM UTC (2318a83)">Diff</a>

Cleanup typos in examples and aria-practices

---

aria-practices.html
examples/grid/LayoutGrids.html
examples/landmarks/HTML5.html
examples/landmarks/at.html
examples/landmarks/banner.html
examples/landmarks/complementary.html
examples/landmarks/contentinfo.html
examples/landmarks/form.html
examples/landmarks/index.html
examples/landmarks/main.html
examples/landmarks/navigation.html
examples/landmarks/region.html
examples/landmarks/resources.html
examples/landmarks/search.html

- Changes all HTML5 References to HTML
- Changes reference in Landmark examples to WHATWG HTML spec
- Modify Header of references section from "Related W3C Documents" to "Related Documents"
- Adds References to [[SVG2]], [[HTML]] and [[HTML-ARIA]] so these appear correctly in the references section
Resolves #1020
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1058.html" title="Last updated on Jun 28, 2019, 11:50 PM UTC (fdfce8c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1058/37da361...fdfce8c.html" title="Last updated on Jun 28, 2019, 11:50 PM UTC (fdfce8c)">Diff</a>

Changed HTML5 references to HTML

---

.travis.yml

travisCI will now check to make sure that a file in the `examples/` folder or `tests/` folder has been edited in a PR before running the example regression tests. If you look at the CI results, it will look as if the regression test pass, but if you look at the results it says "Examples files were not updated, not running example regression tests.".

Conditionally skip regression tests

---

test/util/report_files/ignore_html_files

When running the regression report, it looks at the new index.html file for `data-test-id` meta date. We have an ignore file for this report, so I updated it.

Ignore examples/index.html in regression report

---

examples/radio/radio-2/js/radioButtonActiveDescendant.js
examples/radio/radio-2/js/radioGroupActiveDescendant.js

@mcking65 This pull request fixes a bunch of other linting issues with the JS file, including the RETURN key issue
[Preview of updated radio button 2 example](https://raw.githack.com/w3c/aria-practices/issue1037-remove-return-key-reference/examples/radio/radio-2/radio-2.html)

fixed linting issues and the return key reference for radio 2 example

---

aria-practices.html
examples/disclosure/css/disclosure-navigation.css
examples/disclosure/disclosure-faq.html
examples/disclosure/disclosure-img-long-description.html
examples/disclosure/disclosure-navigation.html
examples/disclosure/js/disclosureMenu.js
examples/index.html
examples/menubar/menubar-1/menubar-1.html
package-lock.json
package.json
test/tests/disclosure-img-long-description.js
test/tests/disclosure-navigation.js
test/util/assertHasFocus.js

Resolves #1028.
Continuation of PR #1036, which contains a long thread of relevant discussion.
[View WIP on disclosure navigation menu example in the issue1028-disclosure-menu-example branch](https://raw.githack.com/w3c/aria-practices/issue1028-disclosure-menu-example/examples/disclosure/disclosure-navigation.html)
> @smhigley, I am done with editorial revisions to the issue1028-disclosure-menu-example feature branch.
> You may want to review the test code. I added documentation for aria-current, which currently does not have a test. I also expanded the documentation for arrow keys, home, and end. Now, there are multiple rows with the same data-test-id, which is OK. However, it might be good to sanity check to make sure the testing covers all the documented behaviors.
> My revisions to …

Add disclosure menu example for issue 1028

---

aria-practices.html

Revise table of name guidance by role for cell and gridcell; supports change made for ARIA issue w3c/aria#993.
[View aria-practices.html in this branch using raw.githack](https://raw.githack.com/w3c/aria-practices/empty-cell-naming-guidance/aria-practices.html)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1081.html" title="Last updated on Jul 13, 2019, 7:23 AM UTC (ff19718)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1081/ea5f0c1...ff19718.html" title="Last updated on Jul 13, 2019, 7:23 AM UTC (ff19718)">Diff</a>

Accessible Name Guidance by Role Table: Advise that empty cells are represented by empty names

---

examples/index.html
scripts/reference-tables.js

@mcking65 
I added the following missing roles to the `reference-table.js` script:
* alert
* alertdialog
* dialog
* log
* marquee
* status
*timer

added missing roles to reference table script'

---

examples/dialog-modal/js/datepicker.js

@mcking65 
This patch fixed a bug with the layout of dates for the calendar grid, based on a month and year.
As you change the month or year the first day of the week is in the wrong day in the grid this patch fixes this bug.
[Preview link of date picker dialog patch](https://raw.githack.com/w3c/aria-practices/datepicker-dialog-calendar-computation-patch/examples/dialog-modal/datepicker-dialog.html)

fixed bug with rendering the grid of dates for a year and month

---

examples/dialog-modal/js/datepicker-day.js

@mcking65 
This patch fixes a bug when clicking on a disabled date in the date picker grid with a pointing device.
It now updates the grid with the new month, before it generated a javascript error due to reference to an undefined value.

Date picker dialog: fix bug when clicking on a disabled day

---

aria-practices.html

remove Math role from those which make their descendants presentational
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1112.html" title="Last updated on Aug 24, 2019, 11:44 PM UTC (836434d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1112/4a29654...836434d.html" title="Last updated on Aug 24, 2019, 11:44 PM UTC (836434d)">Diff</a>

Remove Math role from Children Presentational

---

examples/spinbutton/js/spinbutton-date.js

Fixes issue: https://github.com/w3c/aria-practices/issues/1151
The query selector for the `spinbutton` element was incomplete, which caused it to not query properly in Safari or IE. 
This fix adds in the missing characters to the query so that it queries properly.
Before, clicking on the arrows didn't do anything and the element couldn't be tabbed to:
After, clicking on the arrows updates the value up/down and when tabbing to the picker values, using the up/down arrow keys adjusts the values:

Fix spinbutton example query selector

---

examples/spinbutton/js/spinbutton-date.js

The date picker spin button example would show NaN on all the dates if you tried to loop around to the first date. Also, despite there being a min and max year set, the year could be cycled through potentially infinitely beyond the min or max year.
This was due to the way the min and max values were being queried. The values are set on the DOM nodes for the node with the `spinbutton` role. However, the node that was being queried for those values was the parent node.
This change fixes the node used so that the initial values are set appropriately, and the spinners work as expected.
Before, once you tried to wrap around beyond the last day of the month, all the values would then be set to NaN, and there'd be no way to get it to go back to having real numbers without refreshing the page. …

Spin Button Date Picker Example: Fix incrementing and decrementing past limits

---

examples/tabs/css/tabs.css
examples/tabs/tabs-1/js/tabs.js
examples/tabs/tabs-1/tabs.html
examples/tabs/tabs-2/js/tabs.js
examples/tabs/tabs-2/tabs.html

Tabs Example: use display: none; to hide panels (Issue #1197)

---

examples/tabs/tabs-1/tabs.html
examples/tabs/tabs-2/tabs.html

Add `type` of `button` to `button` elements to conform with the [HTML specification](https://html.spec.whatwg.org/multipage/form-elements.html#the-button-element).
Resolves #1184

Tabs Example: add type of button to button elements (issue #1184)

---

examples/menubar/menubar-2/menubar-2.html
test/tests/menubar_menubar-2.js

To resolve issue #914, adds role group around the menuitemcheckbox elements for font style.
Also updates applicable regression test for the group role.
Also adds missing role="none" on `<li>` elements.
Uses commits from #1144 by @jnurthen, but merges to master instead of apg-1.2.
[View the editor menubar in the compare branch for this PR](https://raw.githack.com/w3c/aria-practices/issue914-menubar2-add-fontstyle-group/examples/menubar/menubar-2/menubar-2.html)

Editor Menubar Example: add group around font style menu item checkboxes

---

aria-practices.html

Closes #1077 
* Adds a new "prohibited" status for Names
* Adds the following  roles to this new status
- caption
- code
- deletion
- emphasis
- generic
- insertion
- paragraph
- presentation
- strong
- subscript
- superscript
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1213.html" title="Last updated on Oct 24, 2019, 12:05 AM UTC (91e3f40)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1213/0223ceb...91e3f40.html" title="Last updated on Oct 24, 2019, 12:05 AM UTC (91e3f40)">Diff</a>

Add prohibited name guidance to naming section

---

.travis.yml

Since this cut over to 13 when it was released, and not all stuff (like node-sass) support latest on day 1

chore: Use LTS Node version instead of "latest"

---

examples/dialog-modal/css/datepicker.css

Corrected the colour contrast of various UI elements so that they pass WCAG minimums.
Resolves #1170

Datepicker Example: Increase colour contrast ratio to pass WCAG (#1170)

---

examples/accordion/css/accordion.css

Resolves a part of https://github.com/w3c/aria-practices/issues/1132

Accordion Example: Correct color contrast (Issue #1132)

---

test/index.js

@smhigley request something like this in https://github.com/w3c/aria-practices/issues/1205.
If you want to write regression tests for an APG example that cover behavior not specifically discussed in the attributes and keyboard interaction tables, you can use the data-test-id `test-additional-behavior`. 
If everyone is ok with it, we can merge this and I'll add it to the documentation!

Allow for tests that do not refer to example tables rows

---

aria-practices.html

Initial draft of a meter pattern (the example implementation is tracked separately in #1105).
Resolves #979
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1189.html" title="Last updated on Nov 5, 2019, 8:10 PM UTC (9525fea)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1189/27e1721...9525fea.html" title="Last updated on Nov 5, 2019, 8:10 PM UTC (9525fea)">Diff</a>

Add meter design pattern

---

aria-practices.html

Fixes #1077.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1231.html" title="Last updated on Nov 6, 2019, 4:30 AM UTC (07a57d4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1231/6ec616f...07a57d4.html" title="Last updated on Nov 6, 2019, 4:30 AM UTC (07a57d4)">Diff</a>

Add naming guidance for blockquote, meter and time roles

---

examples/listbox/css/listbox.css
examples/listbox/js/listbox.js
examples/listbox/listbox-collapsible.html
examples/listbox/listbox-grouped.html
examples/listbox/listbox-rearrangeable.html
examples/listbox/listbox-scrollable.html
test/tests/listbox_collapsible.js
test/tests/listbox_grouped.js

Adds a listbox pattern with grouped options with tests.
Additionally, fixes these bugs with clicking listbox options:
- Clicking any option below the initially visible aria results in the first option being selected instead of the clicked option
- Clicking any option within the initially visible area briefly selects the first option before moving selection to the clicked option
By:
- not immediately selecting the first option when the listbox receives focus (bringing it more inline with native `<select multiple>`
- only initiating automatic listbox scroll when interacting with the keyboard
Resolves #913 
[View this example in the compare branch for this PR](https://raw.githack.com/w3c/aria-practices/913-listbox-groups/examples/listbox/listbox-grouped.html)

Add grouped listbox example

---

aria-practices.html
examples/index.html

Updates:
1. Structural roles section to remove the 3 rows related to associationlist, which is now slated for ARIA 1.3.
2. Structural roles section to remove link outdated link to feedback issue 739.
3. Update indexes of examples.
After merging combobox changes from PR 1255, I will re-reun the reference-tables script, push the updated index, and merge this.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1269.html" title="Last updated on Nov 15, 2019, 4:08 AM UTC (b7acf4b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1269/632bc8a...b7acf4b.html" title="Last updated on Nov 15, 2019, 4:08 AM UTC (b7acf4b)">Diff</a>

Editorial: Final prep of master for working draft publication

---

package.json

This just moves the test globbing to [the Ava configuration](https://github.com/avajs/ava/blob/master/docs/06-configuration.md), which should solve issues where Windows wasn't able to find files.
Some background: npm `scripts` will run command line operations, leveraging whatever syntax features the operating system has in place, which results in ` test/tests/*.js does not exist.` on Windows. This change forces Ava to use [its own internal globbing algorithm](https://github.com/avajs/ava/blob/master/package.json#L91) ([globby](https://github.com/sindresorhus/globby)), which has cross-platform support.

Windows Regression Test Fix

---

aria-practices.html

To resolve #1164, revises the Tab key guidance for tabbing out of the tablist and to the tabpanel.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1274.html" title="Last updated on Jan 23, 2020, 7:28 AM UTC (7d9c7c8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1274/c59168a...7d9c7c8.html" title="Last updated on Jan 23, 2020, 7:28 AM UTC (7d9c7c8)">Diff</a>

Tabs Pattern: Revise tabpanel tabindex guidance for issue 1164

---

aria-practices.html

Partially resolves issue #1150 by adding a warning to the slider patterns.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1186.html" title="Last updated on Jan 27, 2020, 6:30 AM UTC (766ce61)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1186/1a1ba9f...766ce61.html" title="Last updated on Jan 27, 2020, 6:30 AM UTC (766ce61)">Diff</a>

Slider patterns: Provide warning about inability to operate with touch-based assistive technologies due to lack of needed APIs

---

examples/listbox/js/listbox.js

Updates up/down arrow key handling in listbox to only prevent default scroll behavior if focus is actually moved. This allows the up/down arrow keys to scroll the listbox to its upper and lower bounds.
Resolves #1249 
[View listbox example in compare branch for this PR](https://raw.githack.com/w3c/aria-practices/1249-listbox-scroll/examples/listbox/listbox-grouped.html)

Up arrow scrolls to top in grouped listbox

---

aria-practices.html
package-lock.json
package.json
scripts/reference-tables.js
scripts/regression-tests.sh

This fixes the CI error in: https://github.com/w3c/aria-practices/pull/1303
The problem was that AVA is looking for landmark tests because the landmark directory is in the examples directory, and [this script](https://github.com/w3c/aria-practices/blob/master/scripts/regression-tests.sh) tries to run only the tests for the examples that have been edited.
I tested these changes on top of #1303 in this PR, where you can see the CI now passing.
***
<a href="https://pr-preview.s3.amazonaws.com/bocoup/aria-practices/pull/1315.html" title="Last updated on Feb 3, 2020, 7:08 AM UTC (0486008)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1315/d75c28b...bocoup:0486008.html" title="Last updated on Feb 3, 2020, 7:08 AM UTC (0486008)">Diff</a>

Infrastructure: Skip regression testing against landmark example files when they are edited

---

scripts/regression-tests.sh

Contains changes from pull #1315, which couldn't be merged to master because it was behind and GitHub was not giving an update option.

Infrastructure: Don't run regression tests for landmark files

---

examples/spinbutton/js/datepicker-spinbuttons.js
test/tests/spinbutton_datepicker.js

This missing reference was uncovered because this test only fails in February -- for which the function getDaysInMonth had some special handling that lead to an error. Fixed it so the function doesn't error!
[View the spin button example in the compare branch](https://raw.githack.com/bocoup/aria-practices/spinbutton-fix/examples/spinbutton/datepicker-spinbuttons.html)

Spin Button Date Picker Example: Fix February bug

---

examples/menubar/menubar-1/js/MenubarItemLinks.js
examples/menubar/menubar-1/js/PopupMenuItemLinks.js

Issue #1307 reports 2 issues with the navigation menubar example. This PR resolves the scroll to top issue by preventing `menuitem` anchor elements from jumping to `href="#"` (i.e. top of page in Chrome) if they have a menu/submenu.
Here's a [preview link](https://raw.githack.com/w3c/aria-practices/issue1307-scroll-to-top/examples/menubar/menubar-1/menubar-1.html).

Navigation menubar: Fix scroll-to-top problem reported in issue #1307

---

examples/treeview/treeview-1/js/treeitemClick.js

Fixes TreeView problem pointed out in PR https://github.com/w3c/aria-practices/pull/1186#issuecomment-577840796 :
> I have tested https://www.w3.org/TR/wai-aria-practices-1.1/examples/treeview/treeview-1/treeview-1a.html with Talkback (Chrome) and VoiceOver (Safari) and the tree works well with both screenreaders on the smartphone without keyboard. The only problem: The hierarchy of the treeitems is not output.
>
> Note: The following small problem occurs in every browser: in the input field "File or Folder Selected" after selecting a folder not the name of the folder is displayed, but the entire HTML code including all child elements (`<span class="focus">Reports</span><ul role="group">`...)

Tree Examples: Correct result of selecting parent node

---

package-lock.json
package.json

Installed npm-merge-driver as discussed in https://github.com/w3c/aria-practices/pull/1273, a Greenkeeper PR that had a merge conflict. With this utility installed, Greenkeeper merge conflicts will be automatically resolved.
Added documentation to the [infrastructure wiki page](https://github.com/w3c/aria-practices/wiki/APG-Infrastructure#npm-merge-driver).

Install npm-merge-driver

---

package-lock.json
package.json

This is #1325 rebased on latest master. I resolved the conflicts in `package.json` manually, and then ran `npm install` to re-generate `package-lock.json`. However, this appears to have caused some versions to decrease in `package-lock.json` -- for example, `browserlist` changed from 4.8.7 to 4.8.6.
I have the latest npm as far as I can tell (6.13.7).

#1325 rebased (Update stylelint to the latest version 🚀)

---

aria-practices.html

I noticed a link to the grouped listbox example was missing in `aria-practices.html`, so I added it in, with the same wording as on the other example pages.
Single-line PR :)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1341.html#Listbox" title="Last updated on Feb 28, 2020, 10:46 AM UTC (7c51184)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1341/2fd5bf2...7c51184.html" title="Last updated on Feb 28, 2020, 10:46 AM UTC (7c51184)">Diff</a>

Listbox Design Pattern: Add link to grouped listbox example

---

.vnurc
package-lock.json
package.json

Fixes #1346
The message for img looks like it changed in the release

chore: Update vnu-jar to 20.3.16

---

examples/js/utils.js
examples/listbox/js/listbox-rearrangeable.js
examples/listbox/js/listbox.js
examples/listbox/listbox-rearrangeable.html
test/tests/listbox_rearrangeable.js

Resolves #919 
Adds the following functionality:
- Shift + arrow keys
- Control + Shift + home and end
- Control + A
- Shift + Click
Includes tests :)
[Preview link](https://raw.githack.com/w3c/aria-practices/919-listbox-multiselect-keys/examples/listbox/listbox-rearrangeable.html)

Listboxes with Rearrangeable Options: Add keyboard commands for multiple selection

---

aria-practices.html
respec-config.js

***
[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Apr 15, 2020, 5:55 AM UTC)_.
<details>
<summary>More</summary>
PR Preview relies on a number of web services to run. There seems to be an issue with the following one:
:rotating_light: [Spec Generator](https://www.w3.org/2015/labs/) - Spec Generator is the web service used to build specs that rely on ReSpec.
:link: [Related URL](https://labs.w3.org/spec-generator/?type=respec&url=https%3A%2F%2Frawcdn.githack.com%2Fw3c%2Faria-practices%2Fc74e8e46b38c7df5f4c1079f8d3dedf5373af1ab%2Faria-practices.html%3FisPreview%3Dtrue)
```
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```
_If you don't have enough information above to solve the error by yourself …

Fixup ReSpec usage issues

---

examples/combobox/grid-combo.html
examples/dialog-modal/alertdialog.html
examples/dialog-modal/dialog.html
examples/feed/feed.html
examples/grid/LayoutGrids.html
examples/grid/dataGrids.html
examples/listbox/listbox-collapsible.html
examples/listbox/listbox-grouped.html
examples/listbox/listbox-rearrangeable.html
examples/listbox/listbox-scrollable.html
examples/toolbar/help.html
examples/toolbar/toolbar.html

Replaces #1317 because I could not push a rebase to the Bocoup fork.
Resolves #842 by adding examples/js/utils.js to the list of Javascript files in the source code section of the documentation for all example pages that utilize the utils.js..

Multiple Examples: Add utils to js list

---

.eslintrc.json

Now that we're officially dropping IE11 support, we should update `eslint` to allow ES6/ES2015 features.
Related to #1304, #1305

Allow ES6 syntax

---

aria-practices.html
examples/combobox/combobox-autocomplete-both.html
examples/combobox/combobox-autocomplete-list.html
examples/combobox/combobox-autocomplete-none.html
examples/combobox/combobox-select-only.html
examples/combobox/css/select-only.css
examples/combobox/grid-combo.html
examples/combobox/js/select-only.js
examples/index.html
test/tests/combobox_select-only.js
test/util/assertAriaControls.js
test/util/assertAriaDescribedby.js
test/util/assertAriaLabelExists.js
test/util/assertAriaLabelledby.js
test/util/assertAttributeDNE.js
test/util/assertAttributeValues.js
test/util/assertRovingTabindex.js

Resolves #1026 by adding a new select-only combobox example.
NOTE: The build is currently expected to fail; this depends on the es6 PR (#1395) for linting to pass.
[Preview link](https://raw.githack.com/w3c/aria-practices/select-only-combo/examples/combobox/combobox-select-only.html)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1396.html" title="Last updated on Jun 30, 2020, 8:58 PM UTC (6695e84)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1396/162a945...6695e84.html" title="Last updated on Jun 30, 2020, 8:58 PM UTC (6695e84)">Diff</a>

Select-only combobox

---

examples/combobox/combobox-autocomplete-both.html
examples/combobox/combobox-autocomplete-list.html
examples/combobox/combobox-autocomplete-none.html
examples/combobox/grid-combo.html

Fixes the link to the Select-only Combobox Example at the top of each of the 4 other Combobox Examples.

Fix links to select-only combobox

---

examples/combobox/combobox-datepicker.html

Trims the accessibility features section of the combobox date picker proposal in PR #1413.
The objective is to describe the accessibility features that are specific to this implementation, ie, not part of the base design pattern.
[View the compare branch in RawGitHack](https://raw.githack.com/w3c/aria-practices/issue34-ax-features/examples/combobox/combobox-datepicker.html)

Combobox date picker PR: revisions to accessibility features section

---

examples/combobox/combobox-select-only.html

Ticks the checkbox in https://github.com/w3c/aria-practices/pull/1396#issuecomment-627738460 regarding mentioning the places where this diverges from html select behavior in an Accessibility Features section.
[Preview in the compare branch for this PR](https://raw.githack.com/w3c/aria-practices/pr1396-accessibility-features/examples/combobox/combobox-select-only.html)

Select-only Combobox Example: Add Accessibility Features section

---

examples/combobox/combobox-datepicker.html

- controled -> controlled
- enableing -> enabling
This little PR was created without a fork. Just making sure everything works ok. :)
This fixes the [failing build](https://travis-ci.com/github/carmacleod/aria-practices/jobs/361077898) for [PR #1432 Select-only Combobox Example: Add Accessibility Features section](https://github.com/w3c/aria-practices/pull/1432).
Not sure why CSpell didn't catch these before [PR #1413](https://github.com/w3c/aria-practices/pull/1413) was merged? Almost looks like Travis didn't run CSpell that day?

Fix 2 spelling errors caught by CSpell during travis build

---

examples/js/utils.js

Made from #1418  by @MartijnCuppens 
Could not merge #1418 directly because it is from a patch. Replacing with this PR.

utils.js: Recognize file inputs as focusable elements

---

test/tests/menu-button_actions-active-descendant.js

This is a bit unsatisfying of a PR after several hours of investigation, but there are a few flaky tests that I don't want to trip people up until they are fixed.
This PR comments out the tests that I saw failing most frequently in the CI. I commented the tests out so that we would see them reported as "missing" in the regression coverage report. This issue is being used to keep track of the tests: https://github.com/w3c/aria-practices/issues/1415

Temporarily comment out flaky tests

---

aria-practices.html
examples/carousel/carousel-2-tablist.html

In the examples subsection of the carousel pattern, adds a link to the carousel example that uses a tab set for slide control.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1489.html" title="Last updated on Aug 9, 2020, 10:25 PM UTC (68b054b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1489/b1e4f2c...68b054b.html" title="Last updated on Aug 9, 2020, 10:25 PM UTC (68b054b)">Diff</a>

Carousel Pattern: Add link to tabbed carousel example page

---

examples/menubar/menubar-editor.html
examples/menubar/menubar-navigation.html

- removes ../ that is no longer needed after refactoring
- fixes 7 broken links in application menubar example
- fixes 2 broken links in navigation menubar example
(Note that this is a stand-alone PR - there is no linked issue)

Fix broken links in menubar examples

---

scripts/regression-tests.sh

I thing usually when dependencies are updated it includes both package and the lock file, but I've seen some security Dependabot updates that only update the lockfile to fix security issues. This will then trigger the regression tests to make sure lockfile only changes don't regress anything.

chore: Trigger regression for lock file changes

---

.github/workflows/lint-css.yml
.stylelintrc
.stylelintrc.js
.travis.yml
examples/carousel/css/carousel-prev-next.css
examples/carousel/css/carousel-tablist.css
examples/combobox/css/combobox-datepicker.css
examples/combobox/css/select-only.css
examples/dialog-modal/css/datepicker-dialog.css
examples/menubar/css/menubar-editor.css
examples/menubar/css/menubar-navigation.css
examples/radio/css/radio.css

- Swaps Travis for Stylelint step
- Adds the "problem matcher" so issues are commented directly on the lines in PRs
- Fix the styleline config which was in 2 files, and wasn't valid in one, so hasn't been running

chore: Move Stylelint to GitHub action and fix broken config

---

.github/workflows/regression.yml
.travis.yml
scripts/regression-tests.sh

I played around with keeping the parallel job splitting by using letter ranges in a separate branch, but found that this was the most straightforward.
This uses @spectranaut script for limiting the runs to changed files, and adds the GitHub Action path filtering so the job is also only triggered if those files are touched.
@spectranaut should the full suite run on merges to the main branch?

chore: Switch regression test to GitHub Actions

---

.github/dependabot.yml
.github/workflows/lint-css.yml
.github/workflows/regression.yml

Since greenkeeper is shutdown, this will enable the native dependabot PRs to this repo for new version releases of the dependencies.
Closes #1368
Closes #1402
Closes #1382
Closes #1351

Create Dependabot config file

---

.github/workflows/coverage-report.yml
.travis.yml

Currently this is a job that is allowed to fail on Travis CI. This moves it to an action that will leave a comment on the PR if any of the regression related files are changed. Additional pushes will update the same comment instead of continuing to create new ones on the PR.
~~I'm set it so it also runs when the CI config file is touched so you'll see it on this PR~~, but wouldn't on a PR that doesn't touch anything in the `examples` or `test` folder.

Infrastructure: Move Regression coverage to PR comment

---

aria-practices.html
examples/combobox/grid-combo.html
examples/menubar/mb-about.html
examples/menubar/mb-academics.html
examples/menubar/mb-admissions.html
examples/radio/radio-activedescendant.html

Was tring to figure out a link checker solution. Didn't find anything yet, but one did flag thesee (along with the ones @spectranaut is fixing in #1530)
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/1535.html" title="Last updated on Sep 29, 2020, 3:19 PM UTC (556247b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1535/2233e5c...nschonni:556247b.html" title="Last updated on Sep 29, 2020, 3:19 PM UTC (556247b)">Diff</a>

fix: Broken CSS links and anchor tags

---

aria-practices.html
examples/carousel/carousel-2-tablist.html

I  just notice the link to [the first carousel example](https://w3c.github.io/aria-practices/#carousel) is broken in master:
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1530.html" title="Last updated on Sep 30, 2020, 5:36 PM UTC (671f5dd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1530/9d19d94...671f5dd.html" title="Last updated on Sep 30, 2020, 5:36 PM UTC (671f5dd)">Diff</a>

Fix links to Carousel Example with Buttons for Slide Control

---

.github/workflows/cspell-problem-matcher.json
.github/workflows/spelling.yml
.travis.yml

Runs the spellchecking only if the `aria-practices.html` or HTML files in the `example` directory. Add a problem matcher so that comments are left on the lines with spelling issues in PRs and pushes.
The main change that this swap brings, is that GitHub Actions don't have the concept of "allowed failures", so these will be blocking failures.
Closes #1497

Infrastructure: Convert spellcheck to GitHub Action

---

.github/workflows/lint-js.yml
.github/workflows/spelling.yml

They get run as part of the PRs submited and avoids a double build

Infrastructure: Disable push builds for Dependabot

---

.github/workflows/lint-css.yml
.prettierignore
.prettierrc
.stylelintrc
examples/breadcrumb/css/breadcrumb.css
examples/button/css/button.css
examples/carousel/css/carousel-prev-next.css
examples/carousel/css/carousel-tablist.css
examples/checkbox/css/checkbox.css
examples/combobox/css/select-only.css
examples/css/core.css
examples/dialog-modal/css/dialog.css
examples/disclosure/css/disclosure-faq.css
examples/disclosure/css/disclosure-img-long-description.css
examples/disclosure/css/disclosure-navigation.css
examples/grid/css/dataGrids.css
examples/grid/css/layoutGrids.css
examples/landmarks/css/bootstrap-accessibility.css
examples/link/css/link.css
examples/menubar/css/menubar-editor.css
examples/menubar/css/menubar-navigation.css
examples/meter/css/meter.css
examples/radio/css/radio.css
examples/tabs/css/tabs.css
examples/toolbar/css/menuButton.css
package-lock.json
package.json

Related to #1180
Was built off the same branch, so there is overlap with the config, and then suppressing the option in the Stylelint config

Infrastructure: Add Prettier Stylelint config

---

.github/workflows/lint-html.yml
.github/workflows/vnu-jar-problem-matcher.json
.travis.yml

Moves Travis-CI job to GitHub Actions, and adds a problem matcher so errors are identified inline on the files tab of PRs

Infrastructure: Switch HTML linting to GitHub Actions

---

aria-practices.html

Related to https://github.com/w3c/aria/issues/1339 and https://github.com/w3c/aria/pull/1342 on the ARIA repo.
I chose "discretionary" to match the guidance for log.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1572.html" title="Last updated on Oct 23, 2020, 4:35 AM UTC (ee56d0f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1572/c2ee25e...ee56d0f.html" title="Last updated on Oct 23, 2020, 4:35 AM UTC (ee56d0f)">Diff</a>

Accessible Name Guidance by Role Section: Change marquee name from required to discretionary

---

test/tests/button_button-idl.js
test/tests/combobox_autocomplete-both.js
test/tests/combobox_autocomplete-list.js
test/tests/combobox_autocomplete-none.js
test/tests/combobox_grid-combo.js
test/tests/spinbutton_datepicker.js
test/util/assertDotValue.js

https://github.com/w3c/aria-practices/issues/1378
This PR adds tests for: 
- [the button idl example](https://w3c.github.io/aria-practices/examples/button/button_idl.html)
- Fixes some references in the combobox grid text file
- Adds some missing tests for the rest of the combobox tests
- Adds the missing keyboard interaction tests to the spin button date picker

Infrastructure: Add missing test for 6 examples

---

test/tests/link_link.js
test/tests/menu-button_links.js
test/tests/treeview_treeview-2a.js
test/tests/treeview_treeview-2b.js
test/util/replaceExternalLink.js

Fixes issue #1594
Following external links in tests to test key board interactions with links cause many time out related failures in github checks. I replace the four tests to replace the `href` on the dom element with a url fragment to test the keyboard behavior.

Changes tests to not follow external links

---

test/tests/spinbutton_datepicker.js

When you get towards the end of the month and try to add a month, Javascript Date objects start to do unexpected things. This is causing failures in the CI for all regression tests run today. This is the issue:
```javascript
let date = new Date('10/31/2020'); 
date.setMonth(date.getMonth + 1);
```
The second line increases the date by one month, resulting in date being December 1st, 2020, because there is no November 31st.
The fix is to put the day of the month to the 1st using `date.setDate(1)` before doing any math, because all months have the 1st of the month.

Spin Button Date Picker: Fix unreliable date math test

---

examples/css/core.css
examples/treeview/treeview-navigation.html

Wrap caution paragraph/list in a div with w3c "advisement" class, which gives the div a light orange background with a darker orange border on the left.

Add orange box style for the cautionary note

---

cspell.json

Don't spell-check any css background-image urls (including comma-separated urls).
Hopefully, merging this will stop the automated spell-check from failing in PR #1694.

Allow comma or semicolon at end of cspell ignore regex for css background image urls

---

examples/treegrid/css/expand-icon-highlighted.svg
examples/treegrid/css/expand-icon.svg
examples/treegrid/css/treegrid-1.css
examples/treegrid/js/treegrid-1.js
examples/treegrid/treegrid-1.html

Adding the open in Codepen button! This involved moving some SVGs and moving some code.
[Preview](https://raw.githack.com/w3c/aria-practices/codepen-treegrid/examples/treegrid/treegrid-1.html)

Add "Open in Codepen" button to Treegrid example

---

examples/button/button_idl.html
examples/button/js/button_idl.js
test/tests/button_button-idl.js

Add codepen to the Button IDL example using the same pattern as Button example in the https://github.com/w3c/aria-practices/pull/1642. There is no styling for this example, and I checked out code from a month ago and didn't see the styling there either.
[Preview Button IDL Example](https://raw.githack.com/w3c/aria-practices/codepen-button-idl/examples/button/button_idl.html)

Open in codepen: Button IDL 

---

aria-practices.html

- reworks/expands the initial focus section for modal dialogs to include the case of structured content dialogs (not necessarily covered by the "large enough to cause scrolling")
- adds advice about `aria-describedby` and when it's best NOT to use it (for structure-heavy dialogs)
Closes https://github.com/w3c/aria-practices/issues/442
***
<a href="https://pr-preview.s3.amazonaws.com/patrickhlauke/aria-practices/pull/1707.html" title="Last updated on Dec 30, 2020, 8:02 PM UTC (2e3a150)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1707/2c38b7f...patrickhlauke:2e3a150.html" title="Last updated on Dec 30, 2020, 8:02 PM UTC (2e3a150)">Diff</a>

Modal Dialog Pattern: Clarify initial focus and aria-describedby guidance

---

examples/spinbutton/datepicker-spinbuttons.html
test/tests/spinbutton_datepicker.js

https://github.com/w3c/aria-practices/issues/1426 suggests that the behaviour should be updated in the future.
This enables the tests reliably and adds the current undocumented behaviour in the example around some keystrokes.

fix: Spin Button Date tests and sync spec to current behaviour

---

package-lock.json
package.json

Doesn't seem like the dependency is used anymore

chore: Remove run-node dependency

---

examples/accordion/accordion.html
examples/grid/LayoutGrids.html
examples/grid/dataGrids.html
examples/grid/js/dataGrids.js
examples/grid/js/layoutGrids.js
examples/listbox/js/listbox-rearrangeable.js
examples/listbox/listbox-collapsible.html
examples/listbox/listbox-rearrangeable.html
examples/menu-button/menu-button-links.html

Add "Open in Codepen" to 6 more examples!
Githack for review:
- [accordion/accordion.html](https://raw.githack.com/w3c/aria-practices/codepen-implementation-part6/examples/accordion/accordion.html)
- [grid/LayoutGrids.html](https://raw.githack.com/w3c/aria-practices/codepen-implementation-part6/examples/grid/LayoutGrids.html)
- [menu-button/menu-button-links.html](https://raw.githack.com/w3c/aria-practices/codepen-implementation-part6/examples/menu-button/menu-button-links.html)
- [grid/dataGrids.html](https://raw.githack.com/w3c/aria-practices/codepen-implementation-part6/examples/grid/dataGrids.html)
- [listbox/listbox-rearrangeable.html](https://raw.githack.com/w3c/aria-practices/codepen-implementation-part6/examples/listbox/listbox-rearrangeable.html)
- …

Add "Open in codepen" buttons to 6 more examples

---

examples/button/button_idl.html

Fixes #1692 as follows:
- use advisement class to put note in an orange box
- update wording
- include note in codepen
@spectranaut, I've added you as a reviewer because you understand the issue (i.e. the warning needs to be really visible).
Also, please note that I moved the warning paragraph so that it's now part of the CodePen content. I hope you agree that the warning needs to go with the code, at least for now. :)  If the user deletes it from the CodePen, that's on them... ;)
Note also that I added [target="_blank"](https://html.spec.whatwg.org/multipage/browsers.html#valid-browsing-context-name-or-keyword) to the github issue link in the note so that it would open in a new window from the codepen.
[Preview](https://raw.githack.com/w3c/aria-practices/issue1692/examples/button/button_i …

IDL Button example: Make browser support note more visible

---

test/util/assertAttributeCanBeToggled.js

Didn't match function paramater names

test/util/assertAttributeCanBeToggled.js: fix JSDoc param name warnings

---

examples/treeview/js/treeview-navigation.js
test/util/assertAriaOwns.js
test/util/assertAttributeCanBeToggled.js

- Newline after description
- desc -> description
- obj -> object
- String -> string

fix: JSDoc warnings

---

examples/combobox/js/combobox-autocomplete.js
test/tests/combobox_autocomplete-list.js

Adding the change request in this comment: https://github.com/w3c/aria-practices/issues/1619#issuecomment-748882630
In summary:
- Removed the "on blur" event which causes the listbox to close every time the textbox loses focus
- Close the listbox every time there is a click outside of the listbox or text box
- There was a request to close the listbox on `tab`, this is already supported 
[Preview](https://raw.githack.com/w3c/aria-practices/combobox-VOMac-fix/examples/combobox/combobox-autocomplete-list.html)

Editable Combobox With List Autocomplete: Remove "onBlur" events.

---

.github/workflows/deploy.yml
.github/workflows/regression.yml
README.md
scripts/regression-tests.sh

Infrastructure: Update build and test process for default branch rename to main

---

aria-practices.html

Fixes #1800 
- Update Slider and Multi-Thumb Slider Design Pattern warnings
- Fix broken link to slider-color-viewer.html
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1803.html" title="Last updated on Mar 5, 2021, 3:18 PM UTC (293d1c6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1803/a060577...293d1c6.html" title="Last updated on Mar 5, 2021, 3:18 PM UTC (293d1c6)">Diff</a>

Update Slider and Multi-Thumb Slider Design Pattern warnings

---

test/tests/menu-button_links.js

In https://github.com/w3c/aria-practices/pull/1888 the regression test `menu-button_links.js` is repeatedly failing in CI, but I could not reproduce locally. Maybe it's a race condition? Here's an attempt at a fix, to see if it makes the test pass in CI.

Infrastructure: Fix regression test menu-button_links.js to wait for url change

---

aria-practices.html

This PR updates the document to distinguish the disclosure **widget** from the disclosure **control**.
At first, the document refers to the _disclosure_ as the **button**, but then later refers to that button as the disclosure **control**.
---
Note: If **widget** is not the appropriate term, the disclosure examples [[1](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-img-long-description.html)] [[2](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-faq.html)] [[3](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html)] [[4](https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation-hybrid.html)] refer to it as a **design pattern**.
***
<a href="https://pr-preview.s3.amazonaws.com/jonathantneal/aria-prac …

Disclosure: Distinguish the widget from the control

---

aria-practices.html
examples/listbox/listbox-collapsible.html
examples/listbox/listbox-grouped.html
examples/listbox/listbox-rearrangeable.html
examples/listbox/listbox-scrollable.html

Resolves #657
Includes the following two changes:
- Updates the link on the main aria-practices.html page to point to the select-only combobox with a text note
- Adds a deprecation warning to the listbox example page
[Preview link for example page](https://raw.githack.com/w3c/aria-practices/remove-listbox/examples/listbox/listbox-collapsible.html)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1852.html" title="Last updated on Aug 30, 2021, 7:07 AM UTC (b41a23c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1852/c8b1c8c...b41a23c.html" title="Last updated on Aug 30, 2021, 7:07 AM UTC (b41a23c)">Diff</a>

Add deprecation warning to Collapsible Listbox example

---

.github/workflows/coverage-report.yml

Use new syntax to restrict token scope so the job can be re-enabled https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#permissions

Infrastructure: Restrict coverage report to issue-write

---

examples/combobox/js/grid-combo.js
examples/dialog-modal/js/dialog.js
examples/grid/js/dataGrid.js
examples/grid/js/menuButton.js
examples/js/examples.js
examples/listbox/js/listbox.js
examples/listbox/js/toolbar.js
examples/toolbar/js/FormatToolbar.js
test/util/assertNoElements.js
test/util/force-serial.js
test/util/queryElement.js
test/util/queryElements.js
test/util/replaceExternalLink.js
test/util/start-geckodriver.js

Autofixed with `npm run lint:es -- --fix`

Multiple examples: Fix comments to satisfy JSDoc lint warnings

---

examples/index.html

Example's index.html wasn't updated before https://github.com/w3c/aria-practices/pull/1852 landed so CI is currently red for all PRs

fix: Missing update for example index

---

examples/accordion/accordion.html
examples/accordion/css/accordion.css
examples/accordion/js/accordion.js
examples/index.html
test/tests/accordion_accordion.js

Resolves #1819 with the following changes:
[Preview link](https://raw.githack.com/w3c/aria-practices/accordion-defaults/examples/accordion/accordion.html)
General cleanup:
- Updates JS file to a class syntax
- Update classnames to be lowercase
- Fix some border-radius issues in focus styling
- Updated example page wrapper `id` attributes to match other example pages
Behavior changes:
- Removed arrow key and force-one-open functionality
- Updated tests to reflect behavior change
- Removed section that talked about focus styling for "enhanced keyboard interaction"
- Removed arrow key/home/end rows in example page keyboard table
- Removed aria-disabled row in example page attributes table

Update Accordion example code and behavior

---

examples/alert/alert.html

While preparing tests for this example within the ARIA AT project, we determined that testing the different languages used within the alert text would be impossible because it can't be guaranteed that users will have speech engines installed that can voice all of them.  During discussion of how to proceed, the community group couldn't think of a real-world case where having an alert fire in multiple languages at once (rather than a single language expected by the user) would be appropriate or helpful, and so it was proposed that the non-English text just be removed.  This PR accomplishes that task, and capitalises the "H" in "Hello" given its new position at the beginning of the alert text.

Alert example: remove non-English text from alert content"

---

package.json
test/index.js

Use 'DEBUG=1 npm run regression' to opt-in to non-headless.
Fixes #1885
---
[These docs](https://github.com/w3c/aria-practices/wiki/Regression-Tests-for-APG-Example-Pages#running-tests) should be updated when merging this.

Infrastructure: Make 'npm run regression' run as headless by default

---

.htmlhintrc
aria-practices-DeletedSectionsArchive.html
aria-practices.html
coverage/index.html
examples/index.html
examples/landmarks/HTML5.html
examples/landmarks/at.html
examples/landmarks/banner.html
examples/landmarks/complementary.html
examples/landmarks/contentinfo.html
examples/landmarks/form.html
examples/landmarks/index.html
examples/landmarks/main.html
examples/landmarks/navigation.html
examples/landmarks/region.html
examples/landmarks/resources.html
examples/landmarks/search.html
examples/menu-button/menu-button-actions.html
examples/menu-button/menu-button-links.html
examples/menubar/menubar-navigation.html
examples/slider/slider-multithumb.html
examples/treeview/treeview-navigation.html
package.json
scripts/coverage-report.template

Realized that HTMLHint behaves a little differently, and all rules are opt-in
***
<a href="https://pr-preview.s3.amazonaws.com/nschonni/aria-practices/pull/1782.html" title="Last updated on Oct 18, 2021, 1:27 AM UTC (4f4ac21)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/1782/45e9a6c...nschonni:4f4ac21.html" title="Last updated on Oct 18, 2021, 1:27 AM UTC (4f4ac21)">Diff</a>

Infrastructure: chore: Enable and fix additional HTMLHint rules

---

examples/disclosure/disclosure-navigation.html

Hi everyone! This "Open to codepen" is in it's own PR because I'm not totally sure how to move forward with it.
Here is example: [Preview Disclosure Navigation Example](https://raw.githack.com/w3c/aria-practices/codepen-disclosure-navigation/examples/disclosure/disclosure-navigation.html)
The problem is that when we open these examples in codepen, the links send you back to the APG page instead of just updating the main content within the copepen HTML rendering. The reason why is that we send a `base` url to Codepen so that all images and links in the HTML lead back to the APG website.
The codepen example works up until you click a link, so it is probably useful to most programmers. My suggestion is that we leave it in this state for now, and see if there is an elegant solution to keep …

disclosure navigation Example: Add "Open in CodePen" button

---

package-lock.json

Not sure what went out of sync before, but points to the correct
registry URLs now

Infrastructure: fix missing package-lock resolutions

---

.github/workflows/coverage-report.yml
.github/workflows/examples.yml
.github/workflows/lint-css.yml
.github/workflows/lint-html.yml
.github/workflows/lint-js.yml
.github/workflows/regression.yml
.github/workflows/spelling.yml

- Add the action to all jobs using `npm ci`
- Unpin from a version to the main `@2` to avoid churn till the next major version

Infrastructure: Use npm cache in setup-node

---

.github/dependabot.yml

Removes the limit of 10, so some safe dependencies get PRs and
don't get stuck behind a list of 10 that might be harder to land.
Changes to a weekly schedule to at least there should be less
churn with the removed cap.

Infrastructure: Move Depednabot updates weekly

---

.eslintrc.json
aria-practices-DeletedSectionsArchive.html
examples/coding-template/Depricated-MultipleImplementationExample-Template.html
examples/coding-template/Example-Template.html
examples/grid/LayoutGrids.html
examples/grid/dataGrids.html
examples/landmarks/HTML5.html
examples/landmarks/at.html
examples/landmarks/banner.html
examples/landmarks/complementary.html
examples/landmarks/contentinfo.html
examples/landmarks/form.html
examples/landmarks/index.html
examples/landmarks/main.html
examples/landmarks/navigation.html
examples/landmarks/region.html
examples/landmarks/resources.html
examples/landmarks/search.html
examples/listbox/listbox-collapsible.html
examples/listbox/listbox-grouped.html
examples/listbox/listbox-rearrangeable.html
examples/listbox/listbox-scrollable.html
examples/menubar/menubar-navigation.html
package-lock.json
package.json

Allows linting and autofixing of the script tags inside the HTML files

Infrastructure: Add eslint-html plugin

---

examples/feed/feedDisplay.html

Replace the h2 with an h1. There's no reason for that first heading to be an h2.

Feed Example Display Page: Change h2 to h1

---

examples/listbox/listbox-collapsible.html
examples/listbox/listbox-rearrangeable.html
examples/listbox/listbox-scrollable.html

Use h3 for these notes, so that the page doesn't skip from an h2 to an h4 heading.

Listbox Examples: Correct skipped heading level issue; change some h4 to h3.

---

aria-practices.html

Updates the appendix in the apg-1.2 publication branch to provide a change log for the 1.2 release.
[Preview of appendix in compare branch](https://raw.githack.com/w3c/aria-practices/change-log-1.2/aria-practices.html#change_log_2021_november)

Appendix: Update change log for APG 1.2

---

examples/js/notice.html

Provides link to the ARIA and Assistive Technology app home page instead of the aria-at repo and removes 2020 date.
[Preview in raw GitHack](https://raw.githack.com/w3c/aria-practices/update-support-notice/aria-practices.html)

All Example Pages: Update aria-at information in support notice

---

examples/combobox/combobox-autocomplete-list.html
examples/combobox/combobox-autocomplete-none.html

For combobox examples with autocomplete set to none or list, when focus is in the textbox, Enter key closes the listbox if it is open. This commit resolves #855 by updatings the documentation for the Enter key to be consistent with that behavior.

Editable Combobox Examples: Correct enter key documentation for the autocomplete none and list implementations

---

examples/combobox/grid-combo.html

Resolves issue #859 by clarifying the element that that has aria-selected specified.

Combobox example with grid popup: Correct documentation of aria-selected

---

aria-practices.html
examples/checkbox/checkbox-mixed.html
examples/checkbox/checkbox.html

Fixes broken links from main document to checkbox example pages and updates the descriptions of the links.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2144.html" title="Last updated on Nov 15, 2021, 8:14 PM UTC (7b8d65d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2144/0c74238...7b8d65d.html" title="Last updated on Nov 15, 2021, 8:14 PM UTC (7b8d65d)">Diff</a>

Checkbox Examples: Update links and descriptions

---

examples/index.html
examples/menubar/css/menubar-editor.css
examples/menubar/css/menubar-navigation.css
examples/menubar/images/checkbox-checked-focus.svg
examples/menubar/images/checkbox-checked.svg
examples/menubar/images/down-arrow-focus.svg
examples/menubar/images/down-arrow.svg
examples/menubar/images/radio-checked-focus.svg
examples/menubar/images/radio-checked.svg
examples/menubar/images/separator.svg
examples/menubar/images/up-arrow-focus.svg
examples/menubar/images/up-arrow.svg
examples/menubar/js/menubar-editor.js
examples/menubar/js/menubar-navigation.js
examples/menubar/js/style-manager.js
examples/menubar/menubar-editor.html
examples/menubar/menubar-navigation.html
test/tests/menubar_menubar-editor.js

The approach taken here with Unicode symbols in CSS generated content is different from what `menubar-navigation.html` does (which uses inline SVG, without any ARIA attributes). It's further possible to use SVG-in-CSS by using `data:` URLs, as `menubar-navigation.css ` did for the separator (but this patch  changes it to a CSS `linear-gradient` to be consistent with `menubar-editor.css`).
What are the accessibility implications of using Unicode symbols in CSS generated content? Is it good, acceptable, or bad?
[Preview editor menubar in compare branch in raw githack](https://raw.githack.com/w3c/aria-practices/bocoup/menubar-editor-codepen/examples/menubar/menubar-editor.html)
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/1876.html" title="Last updated on Nov 9, …

Add CodePen button to menubar-editor and avoid external SVG

---

aria-practices.html

ARIA 1.3 clarifies when browsers may provide implicit selection.
Those changes to the ARIA specification enable APG to provide guidance on using ariachecked to represent selection in trees. This change updates the roles, states, and properties section of the tree view pattern accordingly.
[Preview changes to tree pattern in RawGitHack](https://raw.githack.com/w3c/aria-practices/tree-pattern-selected/aria-practices.html#TreeView)
Note: revisions to listbox will be addressed separately.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2121.html" title="Last updated on Nov 15, 2021, 2:55 AM UTC (780c24b)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2121/59da387...780c24b.html" title="Last updated on Nov 15, 2021, 2:55 AM UTC …

Tree Pattern: Update selection guidance to include aria-checked

---

aria-practices.html

Updates listbox pattern roles, states, and properties section to:
* Resolve #765 by adding requirements for grouped options.
* Update guidance for indicating selected states to reflect ARIA changes that allow either aria-checked or aria-selected.
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/pull/2137.html" title="Last updated on Nov 15, 2021, 9:02 PM UTC (f19eca1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/aria-practices/2137/c214552...f19eca1.html" title="Last updated on Nov 15, 2021, 9:02 PM UTC (f19eca1)">Diff</a>

Listbox Pattern: Add option grouping and update selection guidance

---

test/util/report.js

Relevant to address an issue found when running the `npm run regression-report` command
> https://github.com/w3c/aria-practices/issues/959#issuecomment-973046818
>
> ```
> $ npm run regression-report
> 
> > aria-practices@0.0.0 regression-report
> > node test/util/report
> 
> Z:\aria-practices\node_modules\htmlparser2\lib\Tokenizer.js:628
>             var c = this.buffer.charCodeAt(this._index);
>                                 ^
> 
> TypeError: this.buffer.charCodeAt is not a function
>     at Tokenizer.parse (Z:\aria-practices\node_modules\htmlparser2\lib\Tokenizer.js:628:33)
>     at Tokenizer.write (Z:\aria-practices\node_modules\htmlparser2\lib\Tokenizer.js:111:14)
>     at Tokenizer.end (Z:\aria-practices\node_modules\htmlparser2\lib\Tokenizer.js:117:18)
>     at Parser.end …
```

Infrastructure: Fix report.js unsupported buffer

---

package-lock.json
package.json

This is only required for husky for publicly published NPM packages that others consume.
Marked package as private to match

Infrastructure: remove pinst

---

test/tests/spinbutton_datepicker.js

The example wraps. So in certain scenarios the control number will be 0. For example, 25th of February “minus” 31 days results in the code example to land on day 28. Due to the module on line 358 that would make the control number 0. This catches that and sets it to dayMax (same logic as in the code example itself).
Hotfix for #2238 (it’s preventing us from merging anything)

fix(#2238): adds catch for when control number is 0

---

examples/landmarks/HTML5.html
examples/landmarks/at.html
examples/landmarks/banner.html
examples/landmarks/complementary.html
examples/landmarks/contentinfo.html
examples/landmarks/css/bootstrap.css
examples/landmarks/form.html
examples/landmarks/index.html
examples/landmarks/main.html
examples/landmarks/navigation.html
examples/landmarks/region.html
examples/landmarks/resources.html
examples/landmarks/search.html

The bootstrap-accessibility.js file was putting role="presentation" on li element in the navigation for absolutely no reason. This causes the entire menu to end up as nav > ul > li[role=presentation]. This seemed unintentional. The fix is just to remove that .navpills class, which doesn't seem to be used in styles.

Landmark Example Pages: Restore list structure in page navigation region

---

.github/workflows/wai-trigger-cleanup.yml
.github/workflows/wai-trigger-deploy.yml
.github/workflows/wai-trigger-pr.yml
scripts/wai-trigger-cleanup.js

To facilitate the [APG Redesign](https://github.com/w3c/wai-aria-practices), this PR implements the workflows outlined in https://github.com/w3c/wai-aria-practices/issues/13.
Related PRs:
- https://github.com/w3c/wai-aria-practices/pull/15.
Workflows:
* wai-trigger-deploy.yml
- Triggers w3c/wai-aria-practices `deploy.yml` workflow to update APG Redesign production URL with latest APG content.
* wai-trigger-pr.yml
- Triggers w3c/wai-aria-practices `pr-create.yml` workflow to populate PR with preview from APG Redesign.
- eg. Note `WAI Preview Link` in https://github.com/howard-e/aria-practices/pull/35.
* wai-trigger-cleanup.yml
- Triggers w3c/wai-aria-practices `remove-branch.yml` workflow to remove branches which are no longer required when PRs have been merged/closed.
___
_This is a …

Infrastructure: Add workflows to support APG Redesign connection with w3c/wai-aria-practices

---

package.json

* Removes `git add` steps from lint-staged instructions because `git add` is now [an automatic step](https://github.com/okonet/lint-staged#v10).
When committing, the following warning message is returned: _⚠ Some of your tasks use `git add` command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index_
Related comments: https://github.com/w3c/aria-practices/pull/2166#issue-1069122296 & https://github.com/w3c/aria-practices/pull/2154#issuecomment-976093237.
cc @nschonni

Infrastructure: cleanup lint-staged steps

---

aria-practices.html

This PR rewrite the introduction section so its content is more appropriate for the about page of the new WAI APG site. It describes the purpose of the APG and its structure for someone who is new to APG. It also explains the purpose of ARIA and sets in the broader context of WAI work.
This revision assumes that the "Fundamentals" page is renamed to "Practices" as requested in w3c/wai-aria-practices#60 and that the "About" page is revised as described in w3c/wai-aria-practices#66.
The new content can be viewed in context under the "Introduction" heading on the [about page in netlify](https://deploy-preview-67--wai-aria-practices2.netlify.app/about/).
___
[WAI Preview Link](https://deploy-preview-67--wai-aria-practices2.netlify.app)
***
[PR …

About Page: Revise intro to better describe WAI-APG site

---

index.html

Several of the resources referenced in the current work section are out-of-date and not ready to be featured on the home page.
This revision is intended to reduce, clarify, and simplify the home page.
___
[WAI Preview Link](https://deploy-preview-95--wai-aria-practices2.netlify.app)

Home Page: Remove current work section and revise contribution section

---

aria-practices.html

The current side bar containing the page TOC for the [naming and describing practice page](https://www.w3.org/WAI/aria/apg/practices/names-and-descriptions/) includes only the following:
1. Introduction
2. What ARE Accessible Names and Descriptions?
3. How Are Name and Description Strings Derived?
4. Accessible Names
5. Accessible Descriptions
Items 4 and 5 are large sections. It is difficult for users to know what is on the page with so many subsections tucked away under them.
This PR proposes removing the headings associated with items 4 and 5 to bump up their subsections and expose them in the page TOC.
[View the new version with 10 items in the page contentes side bar](https://deploy-preview-94--wai-aria-practices2.netlify.app/aria/apg/practices/names-and-descriptions/)
***
[PR …

Providing Accessible Names Practice: Change heading levels to make page TOC more informative

---

README.md

Now that the APG is a section of the WAI web site instead of a W3C note published in W3C Technical Resources,
some of the information in the repository ReadMe is no longer relevant.
This PR removes obsolete information and refers to the new site instead of the previous editor's draft.

Repository ReadMe.md: Update to remove information related to APG as a W3C Note published to TR

---

cspell.json

The 0.2 replaced the old schema awhile ago. I don't believe there is any keys used that are affected in the file.

Infrastructure: bump cSpell config schema version

---

.pr-preview.json

Address #2416
This removes `.pr-preview.json` which seems to allow `pr-preview[bot]` to add a link to the editor's draft (which is no longer being used) onto the parent comment of some PRs.
It also seems to be [overwriting the generated APG redesign link](https://github.com/w3c/aria-practices/issues/2416#issuecomment-1194267587) which is attached to PRs by the `michael-n-cooper-bot` bot. An example exists in the edit history for #2415 parent comment.

Infrastructure: Remove .pr-preview.json

---

.github/workflows/coverage-report.yml
.github/workflows/examples.yml
.github/workflows/regression.yml
.github/workflows/spelling.yml
.github/workflows/wai-trigger-deploy.yml
.github/workflows/wai-trigger-pr.yml

See https://github.com/w3c/aria-practices/issues/2418 for more information about the task. Note that the build will fail until the changes on the move-examples-6 branch (https://github.com/w3c/aria-practices/pull/2441) are approved and merged.

Update GitHub workflows to use new content tree (Issue 2418 task 10)

---

content/patterns/listbox/examples/listbox-rearrangeable.html

Fixes #2193
Adds a note with the wording we discussed in a meeting on the Rearrangeable Listbox multiselect example.

Add note on APG vs. browser multiselect listbox keyboard pattern

---

examples/switch/css/switch-button.css
examples/switch/switch-button.html

___
[WAI Preview Link](https://deploy-preview-160--wai-aria-practices2.netlify.app)
[Preview of Switch using Button Example](https://deploy-preview-160--wai-aria-practices2.netlify.app/aria/apg/example-index/switch/switch-button.html)

Switch Example using Button: Fix white on white bug 

---

.github/workflows/wai-trigger-cleanup.yml
.github/workflows/wai-trigger-pr.yml

This adds support to provide preview links being appended to PRs which have been submitted from forked repositories such as https://github.com/w3c/aria-practices/pull/2437.
This also depends on https://github.com/w3c/wai-aria-practices/pull/162 being approved and merged.
___
[WAI Preview Link](https://deploy-preview-163--wai-aria-practices2.netlify.app)

Infrastructure: Modify GitHub workflow to add Netlify preview links to PRs from forks

---

examples/landmarks/css/common.css
examples/landmarks/main.html
examples/landmarks/resources.html

Updated `commons.css` stylesheet to include underlining all links in the MAIN content.
Edited a resource page to update a link to the latest information.
This pull request is related to issue #2505.  Since the links are now underlined in the main region, color is not the only way to distinguish link content from other content.

Landmark Examples: Underline links in main content

---

examples/checkbox/js/checkbox.js

Fixes #2425.
I chose to move this logic to a `keyup` handler to maintain consistency with HTML checkboxes. If this fix is okay, we should probably make a similar fix to the [Mixed Checkbox example](https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox-mixed.html).

Checkbox Example (Two State): Activate checkbox only on keyup

---

content/patterns/button/button-pattern.html
content/patterns/combobox/combobox-pattern.html
content/patterns/dialog-modal/dialog-modal-pattern.html
content/patterns/feed/feed-pattern.html
content/patterns/grid/grid-pattern.html
content/patterns/link/link-pattern.html
content/patterns/listbox/examples/listbox-rearrangeable.html
content/patterns/listbox/listbox-pattern.html
content/patterns/menubar/menu-and-menubar-pattern.html
content/patterns/meter/meter-pattern.html
content/patterns/radio/radio-group-pattern.html
content/patterns/slider-multithumb/slider-multithumb-pattern.html
content/patterns/slider/slider-pattern.html
content/patterns/spinbutton/spinbutton-pattern.html
content/patterns/table/table-pattern.html
content/patterns/tabs/tabs-pattern.html
content/patterns/toolbar/toolbar-pattern.html
content/patterns/tooltip/tooltip-pattern.html
content/patterns/treegrid/treegrid-pattern.html
content/patterns/treeview/treeview-pattern.html
content/patterns/windowsplitter/windowsplitter-pattern.html
content/practices/keyboard-interface/keyboard-interface-practice.html
content/practices/names-and-descriptions/names-and-descriptions-practice.html

Reformat instances of `class="note"` and `class="warning"`.
For each instance of either class:
* If the class is not on a `div`:
* Wrap the element with the class in a `div`.
* Increase indent of the wrapped element two spaces.
* Delete the class from the wrapped element.
* Add the class to the `div`.
* In the the `div` with the class, add a heading as the first child:
* Make the heading level one deeper than the containing section.
* If the class is "note", set heading text to "Note".
* If the class is "warning", set heading text to "Warning".

Move-Examples: Fix notes and warnings

---

content/shared/js/skipto.js

Changes included in SkipTo version 5.1:
* Supports including headings and landmarks in custom web components.
* Rewritten to use Javascript  modules.
* Change configuration options to allow customization of container element to be customized; default container is `nav` element.
* The APG implementation of SkipTo sets the container to `div` so it does not create a navigation landmark. 
___
[WAI Preview Link](https://deploy-preview-195--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 28 Feb 2023 19:04:02 GMT)._

Infrastructure: Update script that provides skipto menu on all pages to version 5.1

---

.github/workflows/regression.yml
package-lock.json
package.json
test/util/start-geckodriver.js

See #2636.
Bump `ava` and `selenium-webdriver`.
Also _temporarily_ pin the node version to `v16` when executing the `Run regression tests` job. `actions/setup-node@v3` has recently defaulted to using `v18` but that it seems to break the regression tests running in CI in this repository. 
This should be temporary because we'd ideally want to solve what's happening for the latest node LTS version here.
___
[WAI Preview Link](https://deploy-preview-203--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 02 Mar 2023 21:58:20 GMT)._

Infrastructure: Bump `ava` and `selenium-webdriver`

---

.eslintrc.json
content/patterns/listbox/examples/js/listbox-collapsible.js
content/patterns/listbox/examples/js/listbox-rearrangeable.js
content/patterns/listbox/examples/js/listbox-scrollable.js
content/patterns/listbox/examples/js/listbox.js
content/patterns/listbox/examples/js/toolbar.js

Hello, @jongund! During [today's APG Task Force meeting](https://www.w3.org/2023/03/07-aria-apg-minutes.html), I offered to take a look at the linting failures in gh-2622. Here's my proposal for a solution!
It's not exactly what I suggested "off the cuff," because I've gained additional context that influenced my opinion here. Namely: it's that the "global namespace object" pattern is used elsewhere in the project. Although we know there are better methods for code sharing, it seems wise to defer addressing that for another day (when we can address the issue holistically) and to focus today's patch on the stated problem.
Fortunately, your decision to introduce ES6 classes doesn't interfere with the namespace pattern. If we use a "class expression" rather than a "class declaration," we can …

Satisfy linter for gh-2622

---

content/patterns/alert/examples/alert.html
content/patterns/link/examples/link.html
content/patterns/radio/examples/radio-activedescendant.html

Updates three example pages to include a section for AT support:
* Alert
* Link
* Radio Using aria-activedescendant
___
[WAI Preview Link](https://deploy-preview-209--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 30 Mar 2023 19:05:07 GMT)._

Add AT support tables to example pages for alert, link, and radio using activedescendant

---

content/patterns/button/examples/css/button.css

For more information see https://github.com/w3c/aria-practices/issues/2650. 
On the button example there was an interaction between the website template's focus indication implementation and the example's focus indication that resulted in no indicator showing. There was some rightful concern from Howard that naively removing  z-index of -1 might result in a regression that the original author had intended to fix, so I tested the button as thoroughly as I can to cover our bases:
Following the change I tested both the final version as it appears on the website as well as the raw HTML version as it appears in the APG source code, on Mac with Chrome, Firefox and Safari, including with VoiceOver, and on Windows with Chrome, Firefox and Edge, including with NVDA. In all cases the buttons were …

Button Example Page: Fix CSS that caused focus indicator to disappear

---

content/about/introduction/introduction.html

Address a typo noticed at https://github.com/w3c/wai-aria-practices/pull/207#discussion_r1163284579.
* Change `plane and simple` to `plain and simple`.
___
[WAI Preview Link](https://deploy-preview-211--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 11 Apr 2023 21:48:03 GMT)._

Introduction page: Fix typo (change `plane` to `plain`

---

content/patterns/landmarks/landmarks-pattern.html

Resolves #2645 by adding a new landmarks pattern page.
[Netlify preview of the landmarks pattern page](https://deploy-preview-220--aria-practices.netlify.app/aria/apg/patterns/landmarks/)
___
WAI Preview Link [failed to build](https://github.com/w3c/wai-aria-practices/runs/13528623120?check_suite_focus=true) on 'Update site files' step. _(Last tried on Tue, 16 May 2023 18:47:50 GMT)._

Add landmark pattern page

---

content/practices/hiding-semantics/hiding-semantics-practice.html

___
[WAI Preview Link](https://deploy-preview-222--aria-practices.netlify.app/ARIA/apg) _(Last built on Fri, 09 Jun 2023 20:40:42 GMT)._

Hiding Semantics Practice Page: Add missing word "that"

---

content/patterns/checkbox/examples/js/checkbox-mixed.js

This is a follow-up PR to https://github.com/w3c/aria-practices/pull/2518 where [Checkbox Example (Two State)](https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox.html) was changed to only toggle on keyup. I think it makes sense to make the same change to [Checkbox Example (Mixed-State)](https://www.w3.org/WAI/ARIA/apg/example-index/checkbox/checkbox-mixed.html) for consistency.
(Just a head's up, this is a resubmitting of #2541)
___
[WAI Preview Link](https://deploy-preview-231--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 13 Jun 2023 18:40:15 GMT)._

Checkbox Example (Mixed-State): Toggle on keyup to prevent continuous toggling

---

content/shared/js/skipto.js

This update fixes the following issues:
1. Accessible name computation takes into account Firefox when there are img elements in a heading (H1-H6).
2. `skipto.js` will only load once, if the `skipto.js` is loaded more than once the successive loadings will be ignored and send a warning message to the console.
___
[WAI Preview Link](https://deploy-preview-215--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 11 May 2023 14:18:55 GMT)._

Skipto menu on all pages: Update skipto.js script to version 5.1.6

---

content/shared/templates/example-usage-warning.html
package.json

See #2637
Update the path used with `vnu-jar` to `content`.
___
WAI Preview Link [failed to build](https://github.com/w3c/wai-aria-practices/runs/14440459072?check_suite_focus=true) on 'Update site files' step. _(Last tried on Wed, 21 Jun 2023 14:18:40 GMT)._

Infrastructure: Update vnu-jar parameters to remove unused paths

---

content/patterns/combobox/combobox-pattern.html

This PR replaces #2375.
In the "About This Pattern" section of the Combobox Pattern:
* Simplified wording of the first sentence, breaking it int two sentences.
* Divided first paragraph into two paragraphs
* Changed order of sentences.
[View the revised combobox pattern in the compare branch of this PR](https://deploy-preview-235--aria-practices.netlify.app/aria/apg/patterns/combobox/)
* N/A: [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by reviewer_id
* N/A: [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by reviewer_id
* N/A: …

Combobox Pattern: Simplify wording of description in "About This Pattern" section

---

content/patterns/feed/examples/css/feedDisplay.css
content/patterns/feed/examples/js/feedDisplay.js
test/tests/grid_data_grids.js
test/tests/grid_layout_grids.js
test/tests/toolbar_toolbar.js
test/tests/treegrid_treegrid-1.js

Fixes #2628
Possibly also w3c/wai-aria-practices#190 ? Was not clear to me the relation between aria-practices and wai-aria-practices.
Once this is OK, need to remember to deal with issue w3c/wai-aria-practices#225. Again, not sure about the relation, sorry if it shouldn't be mentioned here.
Ah, couple of points.
1) as suggested, I used radio-rating.html as "inspiration" for this fix. The CSS for that file included the following bits:
```
.restaurant-rating svg {
forced-color-adjust: auto;
touch-action: pan-y;
}
.restaurant-rating svg .star-none {
stroke-width: 3px;
stroke: #f8951d;
fill-opacity: 0;
}
```
..., which I did **not** include / copy for the feed example, as they didn't seem necessary. But supposing that I've misunderstood something, I could be wrong about that.
2) Also just …

Feed Example: Convert images to inline SVG

---

content/patterns/alert/examples/alert.html
content/patterns/button/examples/button.html
content/patterns/link/examples/link.html
content/patterns/radio/examples/radio-activedescendant.html

Revises the 4 example pages that have AT support tables to move the AT Support section above the source code sections.
* [Preview alert example page](https://deploy-preview-238--aria-practices.netlify.app/aria/apg/patterns/alert/examples/alert/)
* [Preview button example page](https://deploy-preview-238--aria-practices.netlify.app/aria/apg/patterns/button/examples/button/)
* [Preview link example page](https://deploy-preview-238--aria-practices.netlify.app/aria/apg/patterns/link/examples/link/)
* [Preview radio example page](https://deploy-preview-238--aria-practices.netlify.app/aria/apg/patterns/radio/examples/radio-activedescendant/)
* N/A: [Visual design …

Reposition AT support tables higher on the page

---

content/patterns/switch/examples/switch-checkbox.html

Fix incorrect text about the border width transition.
___
[WAI Preview Link](https://deploy-preview-243--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 13 Jul 2023 19:03:55 GMT)._

Switch Example Using HTML Checkbox: Fix editorial error in accessibility features documentation

---

.github/workflows/regression.yml
test/index.js
test/util/start-geckodriver.js

See #2636 
Node v17+ deprioritised IPv4 addresses in favour of IPv6 with a change to [dns.setDefaultResultOrder](https://nodejs.org/api/dns.html#dnssetdefaultresultorderorder). This [was done](https://github.com/nodejs/node/issues/40702) without a [happy-eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) implementation which meant the loopback address used when running the regression tests resolved to `::1` rather than the IPv4 loopback, `127.0.0.1` which geckodriver expected. So this PR now explicitly uses `127.0.0.1`.
Alternatively, we could have added `--dns-result-order=ipv4first` to the running script, or added `dns.setDefaultResultOrder('ipv4first');`, but would eventually remove it as the happy-eyeballs implementation is now [included in …

Infrastructure: Update `localhost` references for regression tests

---

content/practices/names-and-descriptions/names-and-descriptions-practice.html
content/practices/structural-roles/structural-roles-practice.html

Updates two practice pages to add information about mark role:
1. On page "Structural Roles", adds mark role to table in section "All Structural Roles and Their HTML Equivalents".
2. On page "Providing Accessible Names and Descriptions", adds mark role to table in section"Accessible Name Guidance by Role".
Fixes #1821.
Replaces PR #1826.
* N/A: [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by reviewer_id
* N/A: [Accessibility …

Add guidance for mark role

---

content/patterns/combobox/examples/js/select-only.js

Fixes #2719.
Select only scrollbar would close when user would try to click on it.
worked on with @andreancardona 🎉 
[Preview fixed Select-Only Combobox Example | APG | WAI | W3C](https://deploy-preview-228--aria-practices.netlify.app/aria/apg/patterns/combobox/examples/combobox-select-only/)
* N/A: [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review)
* N/A: [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review)
* N/A: [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review)
___
[WAI Preview …

Select-only Combobox Example: Fix scroll event listener bug

---

cspell.json

Add "Montalvo" to `cspell.json`. It's being flagged by the cspell spellchecker during builds.

Infrastructure: Update cspell.json with Montalvo

---

README.md

Update link to APG Coverage Report in README.md 
The previous path (https://raw.githack.com/w3c/aria-practices/main/coverage/index.html), no longer exists following the APG restructure.
https://raw.githack.com/w3c/aria-practices/main/content/about/coverage-and-quality/coverage-and-quality-report.html seems to be the new location.

ReadMe: Remove section about coverage and quality report

---

content/patterns/treegrid/treegrid-pattern.html

The text in the treegrid pattern differed to the text in the treegrid example. The content of the treegrid pattern was nonsensical as a column only contains one cell so moving focus to the first cell in a column is meaningless.
The behaviour and text of the example are consistent and make logical sense.
Inaccurate text:
Control + Home: If focus is on a cell, moves focus to the first cell in the column.
Control + End: If focus is on a cell, moves focus to the last cell in the column.
Corrected text:
Control + Home: If focus is on a cell, moves focus to the cell in the first row in the same column as the cell that had focus.
Control + End: If focus is on a cell, moves focus to the cell in the last row in the same column as the cell that had focus.
___
[WAI Preview …

Treegrid Pattern keyboard section: Correct text for Control + Home/End

---

content/patterns/treeview/examples/treeview-navigation.html

Incorrect text:
>Because transparent borders are visible on some systems with operating system high contrast settings enabled, transparency cannot be used to create a visual difference between the element that is focused an other elements.
Corrected text:
>Because transparent borders are visible on some systems with operating system high contrast settings enabled, transparency cannot be used to create a visual difference between the element that is focused and other elements.
___
[WAI Preview Link](https://deploy-preview-249--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 10 Aug 2023 07:28:42 GMT)._

Navigation Treeview Example: Correct typo: change 'an' to 'and' in accessibility features

---

content/practices/keyboard-interface/keyboard-interface-practice.html

For consistency with rest of keyboard combinations. 
Conflicts with #1611 style of keyboard combinations (though this one isn't changed there yet)
___
[WAI Preview Link](https://deploy-preview-258--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 19 Sep 2023 09:49:47 GMT)._

Developing a Keyboard Interface Practice: Add missing `kbd` element to macOS re-do command in 'Key Assignment Conventions for Common Functions'

---

content/about/contributing/contributing.html

Edited draft contributors page.
[Jon's draft Contributions Page](https://deploy-preview-247--aria-practices.netlify.app/aria/apg/about/contributing/)
___
[WAI Preview Link](https://deploy-preview-247--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 08 Aug 2023 17:29:36 GMT)._

Edits to draft contributing page by Jon Gunderson

---

content/patterns/combobox/examples/css/combobox-autocomplete.css
content/patterns/combobox/examples/css/grid-combo.css

Resolves #2778 by revising CSS for the following 4 combobox examples so that the space for the input is tall enough to fit the text when viewed in Safari on iOS. Previously, the tops of the letters were chopped off.
* Editable Combobox With Both List and Inline Autocomplete
* Editable Combobox With List Autocomplete
* Editable Combobox without Autocomplete
* Editable Combobox with Grid Popup
Worked on this with @ariellalgilmore 🎉 
Checkout the combobox examples and make sure they work in Safari iOS - it should look like below. 
* [Editable Combobox With Both List and Inline Autocomplete Example | APG | WAI | W3C](https://deploy-preview-253--aria-practices.netlify.app/aria/apg/patterns/combobox/examples/combobox-autocomplete-both/)
* [Editable Combobox With List Autocomplete Example | APG …

Multiple Combobox Examples: Adjust input height so text is fully visible in Safari on iOS

---

.link-checker.js
scripts/link-checker.js

Closes #2809. Follow up on my thoughts in https://github.com/w3c/aria-practices/issues/2809#issuecomment-1733823225.
Should this explicitly check for `user-content-` when checking GitHub links instead?
___
[WAI Preview Link](https://deploy-preview-261--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 02 Oct 2023 13:59:20 GMT)._

Infrastructure: link-checker.js: Check if any of the known `pageIds` include the hash being checked for

---

content/patterns/landmarks/examples/general-principles.html
content/practices/landmark-regions/landmark-regions-practice.html

This PR replaces #2512 by @jnurthen, which was delayed due to the back-end refactor after the redesign launch.
The wording is different from that originally proposed by James; the intent is equivalent.
On both of the following pages, the changes is under the heading "General Principles of Landmark Design". The new content is the 4th bullet under step 2. None of the other content is changed by this PR.
* Practice page: [Landmark Regions | APG | WAI | W3C](https://deploy-preview-265--aria-practices.netlify.app/aria/apg/practices/landmark-regions/#generalprinciplesoflandmarkdesign)
* Example page: [General Principles: Principles: ARIA Landmarks Example](https://deploy-preview-265--aria-practices.netlify.app/aria/apg/patterns/landmarks/examples/general-principles)
*Reviewers:* To learn what …

Landmark Practice: Add note to prevent dialog content wrapped in a landmark

---

content/shared/templates/example-usage-warning.html

See #2838 
Should be merged before https://github.com/w3c/wai-aria-practices/pull/278.
This pull request replaces all "Read This First" h2 headers that were implemented by the build scripts on the example pages for the APG. The build script headers were replaced with "Read This First" h2 headers authored in `example-usage-warning.html`.
___
[WAI Preview Link](https://deploy-preview-279--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 22 Nov 2023 20:17:39 GMT)._

Infrastructure: Change source of h2 for 'Read This First" section header on example pages

---

content/patterns/dialog-modal/examples/css/dialog.css

Relates to #2842.
Initially considered a bottom-padding adjustment, but that would create visual inconsistencies.
This solution seemed best, since, in my opinion, the user would not need to use the "Back to Top" link when the modal is open.
[Modal Dialog Example in compare branch](https://deploy-preview-274--aria-practices.netlify.app/aria/apg/patterns/dialog-modal/examples/dialog/)
* N/A: [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by reviewer_id
* N/A: [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#accessibility_review) by reviewer_id
* N/A: [Test …

Modal Dialog Example: Increase z-index of dialog backdrop

---

content/patterns/feed/examples/feed.html
content/patterns/grid/examples/advanced-data-grid.html
content/patterns/menu-button/examples/menu-button-links.html

This is a minor enhancement related to the PR https://github.com/w3c/wai-aria-practices/pull/281 over in wai-aria-practices, which fixes issue https://github.com/w3c/wai-aria-practices/issues/255. 
That PR addresses inaccuracies with the last modified date listed in the footer of example pages. However I noticed a few examples that did not follow the common convention CSS and JS files are listed. This PR fixes the inconsistencies.
This PR can be reviewed independently from the other PR, and can be merged when ready, before or after 281 is reviewed and merged.
___
[WAI Preview Link](https://deploy-preview-285--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 12 Dec 2023 18:23:15 GMT)._

Infrastructure: Fix inconsistencies in lists of CSS and JS files on 3 example pages (Related to wai-aria-practices issue 255)

---

content/patterns/menu-button/examples/js/menu-button-actions-active-descendant.js
content/patterns/menu-button/examples/js/menu-button-actions.js
content/patterns/menu-button/examples/js/menu-button-links.js
content/patterns/menu-button/examples/menu-button-actions-active-descendant.html
content/patterns/menu-button/examples/menu-button-actions.html
content/patterns/menu-button/examples/menu-button-links.html
content/patterns/menu-button/menu-button-pattern.html
content/patterns/toolbar/examples/js/FontMenu.js
content/patterns/toolbar/examples/toolbar.html
test/tests/menu-button_actions-active-descendant.js
test/tests/menu-button_actions.js
test/tests/menu-button_links.js
test/tests/toolbar_toolbar.js

Closes #697 and #2834 with the following changes:
* Revise menu button pattern to specify that aria-expanded is set to false when the menu is not displayed.
* Revise JS and documentation for 3 menu button examples and the toolbar example to set aria-expanded false when their menus are closed.
* Adjusts corresponding regression tests to ensure the state of expanded is true when the menus are open and false when the menus are closed.
* [Menu Button Pattern](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/menu-button/)
* [Actions Menu Button Example Using aria-activedescendant](https://deploy-preview-272--aria-practices.netlify.app/aria/apg/patterns/menu-button/examples/menu-button-actions-active-descendant/)
* [Actions Menu Button Example Using …

Menu button pattern and 4 examples: Set aria-expanded to false when menus are closed

---

content/practices/names-and-descriptions/names-and-descriptions-practice.html

Inspired by #2871, this is an alternative proposal for resolving #2870.
@patrickhlauke, I originally was looking at writing this as a suggestion in #2871, but it became too complicated. I appreciate the time you took to make a PR; I do not intend to be dismissive of your work on the issue.
In addition to reducing word count, here are the notable editorial differences and my reasons for proposing them. Feedback is welcome on all of them.
1. It describes the preferred syntax first. It seems beneficial to present the most valuable and important information first and enable people to skip over information they may not use.
2. It uses more concrete language for explaining the reason for the preference. In particular, help people understand that it is due to specific AT/Browser combinations not …

Accessible Names Practice: Recommend association via 'for' attribute when using 'label' element

---

scripts/link-checker.js

For more information see https://github.com/w3c/aria-practices/issues/2907#issuecomment-1942226078.
Fixes the link checker in cases where servers behave strangely in the absence of a user-agent header.
Shout out to the Linkinator package where I found the fix for this issue.
___
[WAI Preview Link](https://deploy-preview-298--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 13 Feb 2024 22:05:36 GMT)._

Infrastructure: fix link checker by spoofing user-agent (issue 2907)

---

content/patterns/table/examples/css/sortable-table.css

When all the columns are sortable, none of the header buttons create space in the layout, causing the th row's height to collapse. Fixes #2904.
___
[WAI Preview Link](https://deploy-preview-294--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 25 Jan 2024 23:33:33 GMT)._

Sortable Table Example: Improve CSS so it works when all columns are sortable

---

content/patterns/landmarks/examples/resources.html

Update the list of landmark resources to remove FAE and update link to AInspector for Firefox
___
[WAI Preview Link](https://deploy-preview-306--aria-practices.netlify.app/ARIA/apg) _(Last built on Sun, 07 Apr 2024 17:40:56 GMT)._

Landmark Example Pages: Remove link to FAE and update link to ainspector

---

content/patterns/radio/examples/js/radio-activedescendant.js
content/patterns/radio/examples/js/radio-rating.js
content/patterns/radio/examples/js/radio.js

* The documentation does not include information about the enter key, it was an undocumented behavior
* The regression tests for radio group examples do not include any tests for the enter key
___
[WAI Preview Link](https://deploy-preview-305--aria-practices.netlify.app/ARIA/apg) _(Last built on Sun, 07 Apr 2024 17:43:37 GMT)._

Radio Group Pattern and Examples: Remove Enter key as a way of checking a radio

---

test/tests/disclosure_navigation.js

Fixes #2996.
Update `../tests/disclosure_navigation.js test > "aria-current" attribute on links` to scroll to link before click event.
___
[WAI Preview Link](https://deploy-preview-316--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 25 Apr 2024 19:28:54 GMT)._

Regression Tests: Enable `disclosure_navigation.js` test to scroll to element

---

.github/workflows/lint-css.yml

Saw on a different repo that they've added their own built-in formatter. Could't just add `npm run lint:css -f github` because it confused Prettier, so just split the tasks in the CI config.

Infrastructure: Use Stylelint GitHub Action matcher

---

content/shared/js/skipto.js

See issue in skipto.js repository:
[https://github.com/skipto-landmarks-headings/page-script-5/issues/11] 
[SkipTo Issue 13: Disable shortcuts when in a input or textarea](https://github.com/skipto-landmarks-headings/page-script-5/issues/13)
___
[WAI Preview Link](https://deploy-preview-308--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 23 Apr 2024 18:47:22 GMT)._

Infrastructure: Update skipto.js to fix shortcut key bug for non-english keyboard layouts

---

content/about/coverage-and-quality/coverage-and-quality-report.html
scripts/coverage-report.js

While investigating https://github.com/w3c/aria-practices/pull/3000#issuecomment-2125885984, found that values under the Coding Summary, Coding Practices and Mouse and Pointer Events of the Coverage and Quality Reports page were being significantly and inaccurately increased.
That's because of the `skipto.js` utility included in each pattern's html file was not being ignored in the `coverage-report.js` script and was adding to the metrics when the *.js files were being evaluated.
___
[WAI Preview Link](https://deploy-preview-326--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 23 May 2024 12:59:46 GMT)._

Infrastructure: Exclude `skipto.js` in `coverage-report.js` and report accurate values in Coverage and Quality Reports

---

package-lock.json
package.json
test/util/start-geckodriver.js

Supersedes:
- #3020 
- #3003 
- #3008 
___
[WAI Preview Link](https://deploy-preview-323--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 16 May 2024 17:01:05 GMT)._

Infrastructure: Bump ava from 5.3.1 to 6.1.3. Bump geckodriver from 3.2.0 to 4.4.0. Bump selenium-webdriver from 4.14.0 to 4.20.0

---

package.json

Related to https://github.com/w3c/aria-practices/pull/3024#issuecomment-2189085884.
Currently, using `lint-staged`, the `npm run reference-tables` and `npm run coverage-report` scripts are automatically ran when a git commit happens ONLY if files matching `content/patterns/**/examples/*.html` have been changed.
The generating scripts have been overlooked in that automatic process so this PR adds those (`scripts/coverage-report.*` and `scripts/reference-tables.*`). This should reduce any issues with the `Check examples/index.html / coverage` check if only those script files have been updated in a PR.

Infrastructure: Re-run `npm run reference-tables` and `npm run coverage-report` on source script update

---

content/patterns/slider/examples/css/slider-rating.css
cspell.json

I think the use of `buttontext` system color is a better choice than `linktext` for styling the slider when in Windows 10/11 high contrast modes.   This change makes no difference on high contrast on macOS.
[Preview of updated rating slider](https://deploy-preview-325--aria-practices.netlify.app/aria/apg/patterns/slider/examples/slider-rating/)
___
[WAI Preview Link](https://deploy-preview-325--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 04 Jun 2024 18:26:17 GMT)._

Ratings Slider: Use buttontext instead of linktext system color in high contrast mode

---

test/tests/disclosure_navigation.js

Fixes #2996. The previous fix, #2997 didn't fully resolve the issue described in https://github.com/w3c/aria-practices/issues/2996#issuecomment-2200912116.
Update `../tests/disclosure_navigation.js test > "aria-current" attribute on links` to scroll to link before click event and do click inside `executeScript`.
___
[WAI Preview Link](https://deploy-preview-331--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 01 Jul 2024 20:50:58 GMT)._
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207778172716588

Regression Tests: Enable `disclosure_navigation.js` test to scroll to element and click in `executeScript` context

---

content/practices/read-me-first/read-me-first-practice.html

In the [Read me first page](https://www.w3.org/WAI/ARIA/apg/practices/read-me-first/), section "Principle 2: ARIA Can Both Cloak and Enhance, Creating Both Power and Danger", the anchor tag is not closed in the third example.
Before:
```html
<li><a href="uri1">nav link 1</li>
<li><a href="uri2">nav link 2</li>
```
After:
```html
<li><a href="uri1">nav link 1</a></li>
<li><a href="uri2">nav link 2</a></li>
```
___
[WAI Preview Link](https://deploy-preview-340--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 31 Jul 2024 08:17:27 GMT)._

Read Me First: Close anchor tag in code example

---

content/patterns/table/examples/sortable-table.html

Fixes #3066
updating sr-only text to parenthesis instead of a comma
[Preview Sortable Table Example in compare branch](https://deploy-preview-339--aria-practices.netlify.app/aria/apg/patterns/table/examples/sortable-table/)
___
[WAI Preview Link](https://deploy-preview-339--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 27 Aug 2024 02:57:06 GMT)._

Sortable Table Example: Separate off-screen portion of caption with parenthesis instead of comma

---

content/patterns/dialog-modal/examples/js/dialog.js

Noticed this on another PR, so made the updated according to the rule https://github.com/gajus/eslint-plugin-jsdoc/blob/main/docs/rules/require-returns-check.md#user-content-require-returns-check-passing-examples
___
[WAI Preview Link](https://deploy-preview-341--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 31 Jul 2024 19:29:54 GMT)._

Modal Dialog example: Correct JSDoc warning

---

.github/workflows/wai-trigger-cleanup.yml
.github/workflows/wai-trigger-deploy.yml
.github/workflows/wai-trigger-pr.yml

___
[WAI Preview Link](https://deploy-preview-354--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 18 Sep 2024 14:40:06 GMT)._

Infrastructure: Use w3cGRUNTBOT for authoring PRs and deploying to the WAI website

---

content/patterns/tooltip/tooltip-pattern.html

Resolves #3109.
[Preview revised pattern in compare branch](https://deploy-preview-363--aria-practices.netlify.app/aria/apg/patterns/tooltip/#keyboardinteraction)
___
[WAI Preview Link](https://deploy-preview-363--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 08 Oct 2024 18:38:04 GMT)._

Tooltip Pattern: Clarify mouseout dismissal behavior

---

content/patterns/feed/examples/css/feedDisplay.css

Closes: #3149
Description: Added a fallback foreground color of `#000` to the body element in the Infinite Scrolling Feed Example iframe to address the 1.4.3 contrast failure.
___
[WAI Preview Link](https://deploy-preview-367--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 22 Oct 2024 13:55:25 GMT)._

Infinite Scrolling Feed Example: Add fallback foreground color

---

scripts/link-checker.js

Modifies the error message to detail the actual link that has failed to easily relay the information instead of just providing the line and column number.
Example:
`Found broken external link on content/patterns/accordion/examples/accordion.html:22:13, status was 404` would now be `Found broken external link on content/patterns/accordion/examples/accordion.html:22:13. Link is https://github.com/w3c/aria-practices/projects/8, status is 404`
___
[WAI Preview Link](https://deploy-preview-351--aria-practices.netlify.app/ARIA/apg) _(Last built on Sun, 03 Nov 2024 03:54:35 GMT)._

Infrastructure: Include full link in message when external link errors in link-checker script

---

content/patterns/listbox/examples/js/listbox-collapsible.js
content/patterns/listbox/examples/js/listbox.js
content/patterns/listbox/examples/listbox-collapsible.html
content/patterns/listbox/examples/listbox-scrollable.html
test/tests/listbox_collapsible.js
test/tests/listbox_grouped.js
test/tests/listbox_scrollable.js

Fixes https://github.com/w3c/aria-practices/issues/3138
[Preview changes to Scrollable Listbox Example in compare branch](https://deploy-preview-362--aria-practices.netlify.app/aria/apg/patterns/listbox/examples/listbox-scrollable/)
Not applicable:
___
[WAI Preview Link](https://deploy-preview-362--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 06 Nov 2024 01:45:17 GMT)._

Scrollable Listbox Example: Ad default value 'None' so first item can be focusable on load

---

content/patterns/slider-multithumb/examples/css/slider-multithumb.css
content/patterns/slider-multithumb/examples/js/slider-multithumb.js

Fixes #3118 
Updates the slider to:
* Use `const` and `let` instead of `var`
* Added `click` event on rail to move the minimum and maximum thumbs
[Preview updated multi-thumb slider example in compare branch](https://deploy-preview-369--aria-practices.netlify.app/aria/apg/patterns/slider-multithumb/examples/slider-multithumb/)
Not applicable:
* [Editorial review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#editorial_review) by reviewer_id
* [Visual design review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Review-Process#design_review) by 
* [Accessibility review](https://github.com/w3c/aria-practices/wiki/Pull-Request-Revie …

Multi-Thumb Slider: Add ability to move thumbs by clicking rail

---

.github/dependabot.yml

Not sure how the commit message/PR title will show up for this one. The idea is that all the minor patch updates will be in one PR, but the major version updates will continue to be opened as individual PRs

Infrastructure: Group Minor/Patch Dependabot updates

---

content/practices/grid-and-table-properties/grid-and-table-properties-practice.html

___
[WAI Preview Link](https://deploy-preview-387--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 25 Feb 2025 21:42:24 GMT)._

grid and table properties practice: Fix misplaced greater than symbol in code sample

---

content/practices/landmark-regions/landmark-regions-practice.html

The HTML spec now support the `<search>` element. It maps to an implicit `role=search`.
Fix: https://github.com/w3c/aria-practices/issues/2652
___
[WAI Preview Link](https://deploy-preview-349--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 04 Sep 2024 19:04:38 GMT)._

Landmark Regions Practice: Update `search` landmark guidance to include new HTML `search` element

---

content/patterns/combobox/examples/combobox-autocomplete-list.html

Under the **Accessibility Features** heading, 2nd bullet point, last sub-bullet point, the sentence reads:
"When an element loses focus, its border changes from two pixels to two and padding is increased by two pixels."
This update changes the second occurrence of "two" in the sentence to "zero", following the preceding sentence's logic.
___
[WAI Preview Link](https://deploy-preview-393--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 18 Mar 2025 22:52:38 GMT)._

Editable Combobox With Both List and Inline Autocomplete Example: Editorial correction to accessibility features documentation

---

scripts/link-checker.js

From https://github.com/w3c/aria-practices/pull/3264#issuecomment-2894640892:
> A string of failures on this makes me think this solution is flaky in other areas, particularly with GitHub links. So something to investigate separately as well. 6 failures after my last [commit](https://github.com/w3c/aria-practices/pull/3264/commits/89fbce1d6930d1b76ea0115ad8bcc3ed32306c05) for the following links:
> * https://github.com/w3c/aria-practices/blob/main/.github/workflows/coverage-report.yml (x3)
> * https://github.com/w3c/aria-practices/blob/main/scripts/coverage-report.js (x3)
> * https://ainspector.disability.illinois.edu/
>
> <details>
>
> <summary>expand for list of failing builds</summary>
>
> 1. https://github.com/w3c/aria-practices/actions/runs/15139538651/job/42559608538?pr=3264
> 2. …

Infrastructure: Support rate-limit retries in link-checker

---

.vnurc
package-lock.json
package.json

Ignores the following errors when running `npm run lint:html`:
* The “role” attribute must not be used on a “tr” element which has a “table” ancestor with no “role” attribute, or with a “role” attribute whose value is “table”, “grid”, or “treegrid”.
* The “role” attribute must not be used on a “td” element which has a “table” ancestor with no “role” attribute, or with a “role” attribute whose value is “table”, “grid”, or “treegrid”.
This is already being tracked at https://github.com/validator/validator/issues/1364 and #2082 (but was closed as out of scope). Additional details are in thread at #2082.
<details>
<summary>Detailed failing output:</summary>
```sh
"file:/Users/Projects/aria/aria-practices/content/patterns/treegrid/examples/treegrid-1.html":114.20-115.100: error: The “role” …
```

Infrastructure: Update `vnu-jar` to 24.10.17; ignore warnings

---

content/patterns/landmarks/examples/resources.html
content/patterns/slider/examples/slider-temperature.html

Resolves #3257 
Changes the vertical temperature slider to eliminate redundant announcement of the slider value by screen readers. This change makes the value displayed visually above the slider a child of the slider so its content becomes presentational.
[Vertical Slider Preview](https://deploy-preview-400--aria-practices.netlify.app/aria/apg/patterns/slider/examples/slider-temperature/)
___
[WAI Preview Link](https://deploy-preview-400--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 26 May 2025 02:02:22 GMT)._

Vertical Temperature Slider Example: Eliminate redundant AX tree rendering of value

---

content/patterns/disclosure/examples/css/disclosure-faq.css
content/patterns/disclosure/examples/disclosure-faq.html
content/patterns/disclosure/examples/js/disclosure-button.js
test/tests/disclosure_faq.js

Fix #3269 with the following changes:
* Replaces DL, DT and DD elements with OL and LI elements
* Update CSS for new element selectors
* Revise regression test to expect new element selectors
* Fixed broken regression test
[Preview Example Disclosure (Show/Hide) for Answers to Frequently Asked Questions | APG | WAI | W3C](https://deploy-preview-404--aria-practices.netlify.app/aria/apg/patterns/disclosure/examples/disclosure-faq/)
___
[WAI Preview Link](https://deploy-preview-404--aria-practices.netlify.app/ARIA/apg) _(Last built on Wed, 04 Jun 2025 19:52:21 GMT)._

Example Disclosure for FAQ: Replace description list with unordered list

---

content/patterns/accordion/accordion-pattern.html

Resolves #3300 by removing the trailing colon (:) character at the end of the heading for roles, states, and properties.
___
[WAI Preview Link](https://deploy-preview-408--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 01 Jul 2025 07:45:31 GMT)._

Accordion Pattern: Remove extraneous colon character from heading

---

package-lock.json
package.json
scripts/coverage-report.js

#3303 is failing because it requires a formatting update for `prettier` which [forces additional parentheses](https://prettier.io/blog/2025/06/23/3.6.0#change-17085) around [these `coverage-report.js` comma expressions](https://github.com/w3c/aria-practices/blob/d16d25dd176638c1a04d779bdfebd87ff00ff793/scripts/coverage-report.js#L549:L560) like so:
```diff
-   (example.documentationRoles = addExampleToRoles(getRoles(html), example)),
+   ((example.documentationRoles = addExampleToRoles(getRoles(html), example)),
console.log(
'  [Documentation Roles]: ' + example.documentationRoles.length
-     );
-   (example.documentationAttributes = addExampleToPropertiesAndStates(
+     ));
+   ((example.documentationAttributes = addExampleToPropertiesAndStates(
getPropertiesAndStates(html),
example …
```

Infrastructure: Bump prettier to 3.6.2

---

test/tests/toolbar_toolbar.js

Fix #3331
The [`menuitemradio elements have aria-checked set`](https://github.com/w3c/aria-practices/actions/runs/17052897813/job/48344540282?pr=3354#step:5:61) test now successfully passes in the CI and locally
___
[WAI Preview Link](https://deploy-preview-431--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 19 Aug 2025 18:30:58 GMT)._

Infrastructure: Temp fix to regression test - Fix `toolbar_toolbar.js` by resetting menu button state

---

content/patterns/grid/grid-pattern.html

When grid navigation is off, pressing the Left Arrow or Up Arrow key moves focus between widgets. The description seemed to have the wrap-around behavior reversed, so I corrected it.
[Preview of Grid (Interactive Tabular Data and Layout Containers) Pattern](https://deploy-preview-432--aria-practices.netlify.app/aria/apg/patterns/grid/#keyboardinteraction-settingfocusandnavigatinginsidecells)
___
[WAI Preview Link](https://deploy-preview-432--aria-practices.netlify.app/ARIA/apg) _(Last built on Mon, 01 Sep 2025 07:59:24 GMT)._

Grid Pattern: Correct error in description of left/right arrow behavior when navigating inside a cell

---

cspell.json

Address #3361
Removes `"id=\"(?:[^\\\"]+|\\.)*\""` from `cspell.json`'s `ignoreRegExpList` array. Before this, consider the case where a line is:
```html
<th scope="row"><code>aria-invalid="true"</code></th>
```
The portion, `id="true"` would be excluded leaving cspell to evaluate the following:
```html
<th scope="row"><code>aria-inval</code></th>
```

Infrastructure: Remove 'id=' from cspell's ignoreRegExpList

---

content/patterns/carousel/carousel-pattern.html

In one place, found using slide one (word form), in another slide 2 (digit). 
Best to keep consistent (preferably digits in technical writing: slide 1, slide 2).
___
[WAI Preview Link](https://deploy-preview-435--aria-practices.netlify.app/ARIA/apg) _(Last built on Thu, 11 Sep 2025 08:34:14 GMT)._

Carousel Pattern: Fix inconsistency in use of digits and number words

---

content/practices/keyboard-interface/keyboard-interface-practice.html

Makes two minor editorial improvements to the note about pointer considerations when managing focus:
* Change `must` to `need to` to avoid use of normative sounding language.
* Remove `of course` to avoid superfluous language.
___
[WAI Preview Link](https://deploy-preview-437--aria-practices.netlify.app/ARIA/apg) _(Last built on Tue, 23 Sep 2025 17:31:39 GMT)._

Developing a Keyboard Interface Practice: Editorial revision to note about pointer considerations
